### ISSUE TITLE
Wordpress shows status 502 after add proxy-companion container

### ISSUE THREAD

**Issue by occar421** [JrCs/docker-letsencrypt-nginx-proxy-companion#104]
Hi, I'm new to docker and try using docker.
I made some docker composes and they completely worked with nginx-proxy (port:80).

So, as the next step, I try to use SSL with Let's encrypt and use docker-letsencrypt-nginx-proxy-companion.
I renewed docker composes. Other web pages with nginx container worked correctly as I expected.
But only wordpress compose became not working and status 502. `docker logs blog-wordpress` shows a lot of ...

```
Warning: mysqli::mysqli(): (HY000/1130): Host 'blog-wordpress.blog_internal_net' is not allowed to connect to this My
SQL server in - on line 19

MySQL Connection Error: (1130) Host 'blog-wordpress.blog_internal_net' is not allowed to connect to this MySQL server
```

I didn't meet that error before adding proxy-companion. I assumed that ssl or network have bad effects but I haven't found any good clue.

This is the docker-compose.yml for wordpress. Currently I just modified last 4 rows of environment in service 'wordpress'. These rows work on other web page containers.

``` yml
version: '2'

services:
  db:
    image: mysql:5.7
    container_name: blog-db
    volumes_from:
      # /var/lib/mysql
      - stowage
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - internal_net

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: blog-wordpress
    links:
      - db
    ports:
      - "80"
      - "443"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=wordpress
      - VIRTUAL_HOST=blog.example.net
      - VIRTUAL_NETWORK=base_net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blog.example.net
      - LETSENCRYPT_EMAIL=example@gmail.com
    networks:
      - base_net
      - internal_net
    volumes_from:
      # /var/www/html
      - stowage

  stowage:
    container_name: blog-stowage
    image: busybox
    restart: always
    stdin_open: true
    tty: true
    command: /bin/sh
    networks:
      - internal_net
    volumes:
      - internal_data:/var/lib/mysql
      - internal_data:/var/www/html

networks:
  internal_net:
  base_net:
    external: true

volumes:
  internal_data: {}
```

Once I added port 3306 in service 'db', adding or removing "VIRTUAL_NETWORK", but not working.

Thank you.

**Comment by ggramlich** [comment]
It looks like, you forgot to define WORDPRESS_DB_USER=wordpress for the wordpress container.

**Comment by occar421** [comment]
I defined WORDPRESS_DB_USER=wordpress in environment of wordpress container, then docker-compose down and up. But it's still not working and `docker logs blog-wordpress` showing same error... :mask: 

[Official Quickstart](https://docs.docker.com/compose/wordpress/) works without WORDPRESS_DB_USER env.

**Comment by ryneeverett** [comment]
> I made some docker composes and they completely worked with nginx-proxy (port:80).

> So, as the next step, I try to use SSL with Let's encrypt and use docker-letsencrypt-nginx-proxy-companion.

Pardon if you know this already, but it isn't clear from your post if you realize that this companion requires nginx-proxy and doesn't include or replace it. Therefore it doesn't make sense to show us a compose file where wordpress is listening on ports 80, 443, etc. You still need nginx-proxy.

**Comment by occar421** [comment]
The nginx-proxy container is running and works well on other web page containers from nginx image.

By the way, this is the docker-compose.yml form nginx-proxy and proxy-companion.
```yml
# sudo mkdir /opt/masuqat -p
# curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl | sudo tee /opt/masuqat/nginx.tmpl
# 
# path to certs -> /opt/masuqat/certs
# path to nginx.tmpl -> /opt/masuqat/nginx.tmpl

version: '2'

services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/masuqat/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - net

  cert:
    container_name: proxy_cert
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/masuqat/certs:/etc/nginx/certs:rw
    volumes_from:
      - proxy 
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=proxy_gen

networks:
net:
```
and the piece of the docker-compose.yml for other wep page containers, which run well.
```yml
version: '2'

services:
  primary:
    image: nginx
    container_name: primary
    environment:
      - VIRTUAL_HOST=example.net
      - VIRTUAL_NETWORK=base_net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=example.net
      - LETSENCRYPT_EMAIL=example@gmail.com
    restart: always
    ports:
      - "80"
      - "443"
    networks:
      - base_net

  secondary:
    image: nginx
    container_name: secondary
    environment:
      - VIRTUAL_HOST=second.example.net
      - VIRTUAL_NETWORK=base_net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=second.example.net
      - LETSENCRYPT_EMAIL=example@gmail.com
    restart: always
    ports:
      - "80"
      - "443"
    networks:
      - base_net
# and more...
```
