### ISSUE TITLE
How to combine with another container (like wekan)?

### ISSUE THREAD

**Issue by mareeba** [JrCs/docker-letsencrypt-nginx-proxy-companion#109]
Forgive me if I have misunderstood, but how would one go about combining this with another container such as wekan for example:

https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by SnowMB** [comment]
It's simple. Don't expose the port on the host (it's what the reverse proxy ist for).
Leave out these lines:

> ports:
    - 8081:80

Instead you want to add the following environment variables to the Wekan container:

- VIRTUAL_HOST = domain
- VIRTUAL_PORT = 8081
- LETSENCRYPT_HOST = domain
- LETSENCRYPT_EMAIL = your email that shows up in the certificate

**Comment by mareeba** [comment]
Thanks very much!

So would I need to stop the existing docker containers (ie. the reverse proxy etc) first?
I am currently running this setup:
https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687

Ideally I would like to be able to add additional containers (and remove them) with minimal disruption to the existing running containers.

**Comment by mareeba** [comment]
Thanks my friend.

Okay, so I have the following as my _docker-compose.yml_ but I can't seem to get it to work. It builds fine and I can see the containers running via `docker ps -a` however when I visit the domain I get an nginx 503 error page....?  Any thoughts?  Is there a complete step-by-step guide somewhere perhaps like the one you did for nextcloud+nginx+letsencrypt?

```
wekan:
  image: mquandalle/wekan
  links:
    - wekandb
  environment:
    - MONGO_URL = mongodb://wekandb/wekan
    - ROOT_URL = https://projects.domain.tld
#    - MAIL_URL = smtp://user:pass@mailserver.example.com:25/
#    - MAIL_FROM = wekan-admin@example.com

# Insert environment variables so we can use the existing reverse proxy setup.
    - VIRTUAL_HOST = projects.domain.tld
    - VIRTUAL_PORT = 8081
    - LETSENCRYPT_HOST = projects.domain.tld
    - LETSENCRYPT_EMAIL = our.email@domain.tld


#  ports:
#    - 8081:80

wekandb:
   image: mongo
   volumes:
     - /mnt/docker/wekan/data:/data/db
```
