### ISSUE TITLE
Examples no longer function

### ISSUE THREAD

**Issue by 1beb** [JrCs/docker-letsencrypt-nginx-proxy-companion#117]
I was only able to use the examples by using an older version of nginx-gen and letsencrypt-nginx-proxy-companion v1.1, specifically 0.5.0

```
...
nginx-gen:
  links:
    - "nginx1"
  image: jwilder/docker-gen:0.5.0 # THIS
...

letsencrypt-nginx-proxy-companion:
  links:
    - "nginx1"
  image: jrcs/letsencrypt-nginx-proxy-companion:v1.1
...
```
