### ISSUE TITLE
nginx upstream section not populated correctly

### ISSUE THREAD

**Issue by awesomescot** [JrCs/docker-letsencrypt-nginx-proxy-companion#123]
I'm working with the exmaples from here https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples.  The v2 docker-compose works out of the box.  But if I just swap the image of the simple-site to my own image the upstream section in nginx is no longer correct.  Here is an example.

When simple-site is using the nginx image I get an upstream that looks like this:
```
upstream test.example.com {
   # Container: simple-site@nginx-proxy
   server simple-site:80;
}
```

But when I swap in my image the upstream looks like this:
```
upstream test.example.com {
           # simple-site
           server :8081;
}
```

I'm not sure where it's getting the port 8081 from.  Here is my docker-compse.yml file.
```
 simple-site:
    image: kharatsa/strack:latest
    container_name: simple-site
    environment:
      - STT_LISTEN_PORT=80
      - VIRTUAL_HOST=test.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.example.com
      - LETSENCRYPT_EMAIL=test@example.com
      - LETSENCRYPT_TEST=true
    networks:
      - proxy-tier
```

And as you can see here is the image I'm using:  https://hub.docker.com/r/kharatsa/strack/~/dockerfile/

Is the expose in the docker file, or somehow the app forcing it to pick up port 8081?  And why is the upstream section not getting filled out correctly?

Thanks.
