### ISSUE TITLE
Not working, no errors in logs

### ISSUE THREAD

**Issue by JamesBewley** [JrCs/docker-letsencrypt-nginx-proxy-companion#147]
Hi,

This is exactly the thing I need and would love to get it working.

I have an nginx proxy running and this container running along with the three directories created on the docker host and mounted on the containers as per the instructions:

/etc/nginx/certs
/etc/nginx/vhost.d
/usr/share/nginx/html

When I restart the letsencrypt container I can see it has picked up the LETSENCRYPT_HOST on my target container and sets about getting a cert.  But it fails and nothing appears to get written to vhost.d or html.  All i get is an empty directory for the domain in /etc/nginx/certs.

`WARNING:simp_le:1303: www.domain.com was not successfully self-verified`

any ideas what to check?

**Comment by jslatts** [comment]
I am getting the not-successfully self-verified error too followed by a subsequent acme challenge failure. I've explored a few different suggestions from some of the other open issues here (patched docker images) but nothing has worked for me.

**Comment by JrCs** [comment]
Look at the url that simp_le give you.
You can find why your certificate can't be create.

**Comment by JamesBewley** [comment]
It fails because this container isn't serving up the file, nginx is simply passing the request onto my container which obviously returns 403 as it doesn't exist.

Does the html directory need to be the same folder servered up by my web page? if so how do you deal with multiple web servers/containers?

Sure this need to be reopened?

**Comment by JrCs** [comment]
This not the container that serve the file but nginx proxy container

**Comment by JamesBewley** [comment]
So what needs to be configured above and beyond what is described in the
instructions?

**Comment by dmartinpro** [comment]
I think I'm facing the exact same problem. Could you please explain what's wrong?

**Comment by JamesBewley** [comment]
I have no idea what the issue is but I had this problem in docker version 1.9

I now have it working on Debian using docker version 1.13 from the following repo:
`deb https://apt.dockerproject.org/repo debian-jessie main`

Make the directories:
`mkdir -p /etc/ssl/letsencrypt /etc/nginx/vhost.d /usr/share/nginx/html`

And the following docker compose as a test:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
    - /etc/ssl/letsencrypt:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
    - "80:80"
    - "443:443"
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
    - /etc/ssl/letsencrypt:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
    - nginx-proxy
  hello-world:
    image: tutum/hello-world
    environment:
    - VIRTUAL_HOST=domain.com,www.domain.com
    - LETSENCRYPT_HOST=domain.com,www.domain.com
    - LETSENCRYPT_EMAIL=admin@domain.com
```
