### ISSUE TITLE
Any way to manually renew a certificate?

### ISSUE THREAD

**Issue by victor-lund** [JrCs/docker-letsencrypt-nginx-proxy-companion#148]
So, I have a container that by some reason is not getting one of it's certificate updated automatically. It is configured as follows:
```
  prod-api:
    container_name: prod_api
    build:
      context: ../nginx-php7-fpm
      dockerfile: Dockerfile
    volumes:
      - "./apirepo/conf.d/:/etc/nginx/conf.d"
      - "./apirepo/site/:/var/www/html"
    environment:
      - VIRTUAL_HOST=api.mydomain.com, secondary.api.mydomain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.mydomain.com, secondary.api.mydomain.com
      - LETSENCRYPT_EMAIL=info@mydomain.com
     ...
    networks:
      - proxy-tier
```
So, by some reason "secondary.api.mydomain.com" is not getting automatically renewed - but "api.mydomain.com" does.

I need - with as little downtime as possible(!) - manually renew the problematic domain, but I am not really sure what would be the right approach. Also, I would be interested in knowing why the domain is not getting renewed automatically. When logging the proxy container, the secondary domain is mentioned but recently I have started getting mails from LetsEncrypt that "secondary.api.mydomain.com" soon will expiring..!

```
letsencrypt-nginx-proxy-companion    | 2017-01-13T14:13:20.761075758Z Sleep for 3600s
letsencrypt-nginx-proxy-companion    | 2017-01-13T15:13:20.788940814Z Creating/renewal api.mydomain.com certificates... (api.mydomain.com  secondary.api.mydomain.com)
letsencrypt-nginx-proxy-companion    | 2017-01-13T15:13:21.644645809Z 2017-01-13 15:13:21,643:INFO:simp_le:1383: Certificates already exist and renewal is not necessary, exiting with status code 1.
```
Anyone knows either how i can get the automatic renewal process to work properly again or alternatively how i can manually renew the faulty domain..?

Any ideas or insights would be much appreciated!
