### ISSUE TITLE
Compose V3 Compatiblity - fix volume_from

### ISSUE THREAD

**Issue by Berndinox** [JrCs/docker-letsencrypt-nginx-proxy-companion#159]
Cause with compose V3 "**volumes_from**" is **decrapted** and mapping global volumes is the prefered way the Lets-Encrypt container is not able anymore the retriev the Nginx Proxy Container ID, see:

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/entrypoint.sh#L28-L35

**please** provide a way to get the Container ID in another way, supported with compose v3!

Here my compose v3 example:

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=berndklaus.at
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - nginx:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 30s
      mode: global
      update_config:
        parallelism: 1
        delay: 30s

  nginx-letsencrypt:
    image: JrCs/docker-letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - nginx:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        window: 30s
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s


volumes:
  certs:
  vhost:
  nginx:
```

Error after starting the Stack:
```
Error: can't get nginx-proxy container id !
Check that you use the --volumes-from option to mount volumes from the nginx-proxy.
```
