### ISSUE TITLE
nginx-proxy's DEFAULT_HOST

### ISSUE THREAD

**Issue by rgarrigue** [JrCs/docker-letsencrypt-nginx-proxy-companion#16]
Hi @JrCs 

First of all, very good job here, I really appreciate your stuff coming in nicely in my homemade setup :-)

I got a question regarding nginx-proxy's DEFAULT_HOST param. How do you configure the env variables for domain.tld to use his own certificate instead of subdomain.domain.tld? 

Since that may not be clear, here's my docker-compose

```
proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /opt/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
#    environment:
        #    - DEFAULT_HOST=blog.${DOMAIN}
        #    - LETSENCRYPT_HOST=${DOMAIN}
        #    - LETSENCRYPT_EMAIL=me@${DOMAIN}

# Certificate for nginx-proxy
letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /opt/certs:/etc/nginx/certs:rw
    volumes_from:
    - proxy

blog:
    image: ghost
    container_name: blog
    restart: unless-stopped
    links:
    - proxy
    volumes:
    - /opt/ghost:/var/lib/ghost
    environment:
    - VIRTUAL_HOST=${DOMAIN},blog.${DOMAIN}
    # - VIRTUAL_PROTO=https
    - LETSENCRYPT_HOST=${DOMAIN},blog.${DOMAIN}
    - LETSENCRYPT_EMAIL=me@${DOMAIN}
```  

If I uncomment DEFAULT_HOST and remove ${DOMAIN} from blog's virtual_host, browsing to domain.tld Firefox complain that it's using blog.domain.tld. 

I fixed it giving the domain directly to the blog, but I don't like it. How can I improve it ? 

Thanks & best regards,
