### ISSUE TITLE
Automatic cert renewal fails

### ISSUE THREAD

**Issue by enguerranws** [JrCs/docker-letsencrypt-nginx-proxy-companion#161]
Hi,

I'm using this container for a year now, never had any issue, so, first of all: thanks!

But today, I having an issue: on of my website cert is outdated (ERR_CERT_DATE_INVALID) since 7am. So I guess the container didn't renew my cert on this domain.

When I log the container, it throws an error:
```
letsencrypt-gen                      | Creating/renewal gitlab.enguerranweiss.com certificates... (gitlab.enguerranweiss.com)
letsencrypt-gen                      | 2017-02-02 12:19:53,368:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
letsencrypt-gen                      | Traceback (most recent call last):
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
letsencrypt-gen                      |     return main_with_exceptions(cli_args)
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
letsencrypt-gen                      |     persist_new_data(args, existing_data)
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
letsencrypt-gen                      |     client = registered_client(args, existing_data.account_key)
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
letsencrypt-gen                      |     client = acme_client.Client(directory=args.server, key=key, net=net)
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
letsencrypt-gen                      |     self.net.get(directory).json())
letsencrypt-gen                      |   File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
letsencrypt-gen                      |     raise jose.DeserializationError(str(error))
letsencrypt-gen                      | DeserializationError: Deserialization error: Wrong directory fields
letsencrypt-gen                      | 
letsencrypt-gen                      | Unhandled error has happened, traceback is above
```

What I understand is letsencrypt-gen can see the cert is outdated, regenerate the cert, but can't write it in the directory? So, here's my docker-compose.yml:

```
nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  links:
    - gitlab:gitlab

  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./letsencrypt/certs:/etc/nginx/certs:ro"
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-gen
  volumes_from:
    - nginx-proxy
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./letsencrypt/certs:/etc/nginx/certs:rw"
```

What do I miss there?
