### ISSUE TITLE
Support for static reverse proxying with SSL

### ISSUE THREAD

**Issue by mossholderm** [JrCs/docker-letsencrypt-nginx-proxy-companion#164]
Add support for proxy destinations that are "off-box" and not in docker containers. For example, It would be great to be able to have an encrypted connection land on the nginx-proxy docker container, and then travel unencrypted to the destination server (which isn't a container).

nginx-proxy supports adding a configuration file to achieve this end, but nginx-letsencrypt has no method to handle generating/managing the certificates for this sort of situation.

Perhaps permit allowing some environment variables for passing in additional hostnames/emails for certificates that should be managed, regardless of container existence?

**Comment by ryneeverett** [comment]
Dupe of #127, though that one was arguably never resolved.

**Comment by ForsakenHarmony** [comment]
Yeah, only a workaround, would be interested in this

**Comment by JrCs** [comment]
The best is perhaps to use another solution like [traefik](https://traefik.io)

**Comment by augusteo** [comment]
if you are still having problem with it, I solved it by using another nginx container to serve the static directory, like so:

```yaml
# other lines

static-main-site:
     restart: always
     image: nginx:alpine
     volumes:
       - ./static/path:/usr/share/nginx/html:ro
     environment:
       - VIRTUAL_HOST=www.domain.com,domain.com
       - VIRTUAL_NETWORK=nginx-proxy
       - VIRTUAL_PORT=80
       - LETSENCRYPT_HOST=www.domain.com,domain.com
       - LETSENCRYPT_EMAIL=mail@gmail.com
```
