### ISSUE TITLE
[HELP] How to use with custom nginx proxy?

### ISSUE THREAD

**Issue by oleynikd** [JrCs/docker-letsencrypt-nginx-proxy-companion#174]
Hi,

First of all, thank you for such a great tool!

Recently I switched to `network_mode: "host"` for all my containers and I can't get lets encrypt companion to work now.

Here's typical docker-compose:

```yaml
version: '2'
services:

  rproxy:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile_stage_host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
      - /etc/nginx/vhost.d
      - /certs/ssl:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"

  web_client_server:
    build:
      context: ./web_client_server
      dockerfile: Dockerfile_nginx_stage_host
    environment:
      LETSENCRYPT_HOST: "mydomain.com"
      LETSENCRYPT_EMAIL: "admin@mydomain.com"
    restart: always
    expose:
      - "8080"
    network_mode: "host"

  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /certs/ssl:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
     - rproxy

```

My rproxy is configured to something like:

```nginx
server {

    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/nginx/certs/mydomain.com.crt;
    ssl_certificate_key /etc/nginx/certs/mydomain.com.key;

    ssl on;
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    server_name mydomain.com;

    location / {
        proxy_pass http://localhost:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```

When I start `letsencrypt-nginx-proxy-companion` container it says:
```
ssl_1                | Sleep for 3600s
ssl_1                | 2017/02/17 01:48:50 Generated '/app/letsencrypt_service_data' from 0 containers
ssl_1                | 2017/02/17 01:48:50 Running '/app/update_certs'
ssl_1                | 2017/02/17 01:48:50 Watching docker events
```

Obviously there are no certs generated... Why doesn't `letsencrypt-nginx-proxy-companion` see the `web_client_server` container???

Thanks.
