### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by arthurvi** [JrCs/docker-letsencrypt-nginx-proxy-companion#211]
Certificates are not renewing. I get the error: CA marked some of the authorizations as invalid.
When I look at the logs, I see that the result is unexpected by Letsencrypt. When I look at my custom server, behind the nginx proxy, I can see the incoming requests for .well-known/acme-challenge.

This should not happen right? Nginx should handle the .well-known/acme-challenge request and not pass it to the server behind nginx? How can I prevent this and let Nginx do the .well-known/acme-challenge so my certificates renew automatically.

**Comment by lounagen** [comment]
@arthurvi, if you haven't done it for the last month, you should docker pull your letsencrypt companion image.
The fix #192 for the exact same issue was merged and released last month

**Comment by IVData** [comment]
I'm on the latest version and I am having exactly the same issue. Letsencrypt challenge requests are passed onto the container behind the proxy, which results in a 404 being passed back to LE.

**Comment by buchdag** [comment]
I'm having this too BUT right after that I get another request that nginx handles correctly and the validation ends up succeeding despite the _"CA marked some of the authorizations as invalid."_ warning. I don't get what's going on at all.

I was already using a version of the container including #192 when I noticed this behavior.

**Comment by arthurvi** [comment]
I am running the latest version but the problem still exists. The log on letsencrypt keeps saying "Invalid response" because my API server is handling the request, not the Nginx prox in front. Anything I can try?

**Comment by markhaasjes** [comment]
I'm facing the same issue. I'm able to go to the link itself but validation fails.

```
ERROR:acme.challenges:311: Unable to reach http://mywebsite.com/.well-known/acme-challenge/longHashDHz80NFyKUEM24Z4: HTTPConnectionPool(host='mywebsite.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/longHashDHz80NFyKUEM24Z4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f3ae0cf4350>: Failed to establish a new connection: [Errno 99] Address not available',))
```

**Comment by IVData** [comment]
I seem to have solved my issue by removing my certs folder and letting the letsencrypt companion container start from scratch.

Also make sure you have the vhosts folder mounted on nginx-proxy =)

**Comment by helderco** [comment]
That only delays the problem, when those new certificates need to be renewed again.

Any solution yet?

**Comment by helderco** [comment]
Removing the certificates doesn't help me. It creates empty folders for each domain, same validation error. I have a certificate that expires tomorrow, what to do?

**Comment by buchdag** [comment]
Sounds like misconfiguration or outdated container somewhere, one of my own production setups correctly renewed two certificates the past two weeks, and correctly generated a new one for testing purpose just now.

```
nginx-proxy-le | 2017-06-14 22:07:26,126:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
nginx-proxy-le | 2017-06-14 22:07:27,307:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): test.abcde.com
nginx-proxy    | test.abcde.com 172.18.0.1 - - [14/Jun/2017:22:07:27 +0000] "GET /.well-known/acme-challenge/FzjWnaKV8NJLeseNr8AyH0Ky3R0wWMt49qUa5L62QTA HTTP/1.1" 200 87 "-" "python-requests/2.8.1"
nginx-proxy-le | 2017-06-14 22:07:27,328:INFO:simp_le:1305: test.abcde.com was successfully self-verified
nginx-proxy-le | 2017-06-14 22:07:27,573:INFO:simp_le:1313: Generating new certificate private key
nginx-proxy    | test.abcde.com 66.133.109.36 - - [14/Jun/2017:22:07:27 +0000] "GET /.well-known/acme-challenge/FzjWnaKV8NJLeseNr8AyH0Ky3R0wWMt49qUa5L62QTA HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy-le | 2017-06-14 22:07:28,954:INFO:simp_le:391: Saving account_key.json
nginx-proxy-le | 2017-06-14 22:07:28,956:INFO:simp_le:391: Saving key.pem
nginx-proxy-le | 2017-06-14 22:07:28,957:INFO:simp_le:391: Saving chain.pem
nginx-proxy-le | 2017-06-14 22:07:28,958:INFO:simp_le:391: Saving fullchain.pem
nginx-proxy-le | 2017-06-14 22:07:28,958:INFO:simp_le:391: Saving cert.pem
nginx-proxy-le | Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
```

No LE challenge request passed to the proxyed container anymore, I have no idea why I got that last month on another server, I probably had a configuration issue myself that I don't even remember fixing.

Could you tell us more about how you run the nginx-proxy + letsencrypt-companion containers ?

**Comment by helderco** [comment]
I use docker cloud, with the following stack:

```
letsencrypt:
  image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
  volumes_from:
    - nginx
nginx:
  image: 'jwilder/nginx-proxy:alpine'
  labels:
    com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
  ports:
    - '80:80'
    - '443:443'
  restart: always
  volumes:
    - '/root/nginx/certs:/etc/nginx/certs'
    - '/root/nginx/conf.d:/etc/nginx/conf.d'
    - '/root/nginx/vhost.d:/etc/nginx/vhost.d'
    - '/root/docker-gen/nginx.tmpl:/app/nginx.tmpl:ro'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/apps/letsencrypt:/usr/share/nginx/html'
    - '/apps:/var/www'
    - '/root/nginx/htpasswd:/etc/nginx/htpasswd'
```

**Comment by buchdag** [comment]
Unfortunately I am totally unfamiliar both with docker cloud and with the single container approach to nginx-proxy, so I don't think I'll be able to help you troubleshoot much. If it can be of any help, here is my working docker-compose file: 

```
version: '3'

services:
  nginx:
    image: nginx:1.13.1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'

  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx
      - dockergen
    environment:
      NGINX_DOCKER_GEN_CONTAINER: 'nginx-proxy-gen'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxyed containers. 

networks:
  default:
    external:
      name: nginx-proxy
```

I get the nginx.tmpl file [(the exact version I'm using right now is this one)](https://github.com/jwilder/nginx-proxy/blob/985c46d8b56f2ee4652e9d75b49c128c14bee328/nginx.tmpl), create the network nginx-proxy, then I'm good to go.

You can use `volumes_from:` if you switch back to `version: '2'`
