### ISSUE TITLE
Too many certificates already issued for exact set of domains

### ISSUE THREAD

**Issue by Steven-Harris** [JrCs/docker-letsencrypt-nginx-proxy-companion#216]
## Error
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: example.com

## Issue
I have deploying a lot recently to my site and I ran into an issue today there Let's encrypt has stop validating my requests.

After researching I discovered that there is a limit on the let's encrypt beta to 5 certs request a week.

## Possible Solution
Can the docker image be change to the public version? Or could there be a build in system to tell let's encrypt to delete the old records when restarting the container?

### Docker compose
[https://github.com/Steven-Harris/site/blob/master/docker-compose.yml](https://github.com/Steven-Harris/site/blob/master/docker-compose.yml)

**Comment by buchdag** [comment]
There is no "beta" or "public" version of letsencrypt (well letsencrypt **was** in beta at some point but that's irrelevant to your issue).

The duplicate certificate limit of 5 certs a week is the same for everyone and is enforced to ensure "fair usage by as many people as possible" : https://letsencrypt.org/docs/rate-limits/

**Comment by Steven-Harris** [comment]
@buchdag  So, the certs should be persisting and they are not? Do you see anything that I am missing in my docker-compose?

**Comment by buchdag** [comment]
yep : you don't use named volumes or host directories as volume so every time you go through a cycle of `docker-compose down` and `docker-compose up` or change your docker-compose.yml, docker-compose will re-create new randomly named volumes instead of using the previous ones.

That can be easily verified with `docker volume ls`, you should see a huge number of randomly named volumes.

So one way to fix this is to use named volumes in your docker-compose.yml : 

```
version: '2'

services:

[...]

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks: 
      - "proxy-tier"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

volumes:
  vhost:
  html:
  certs:

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

Those will be correctly reused across restarts or docker-compose.yml modifications.

You can also use host directories as you did for the commented out ghost container.

Also, following this container documentation, you should add 

```
      labels:
        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
```

to the nginx-proxy service definition.

**Comment by Steven-Harris** [comment]
Awesome! Thanks for the help. That makes sense and I will make those changes.

**Comment by claym** [comment]
Had a question on this - if i'm explicitly importing volumes from my host, is using named volumes still required?

Like if I did

```
    volumes:
      - "/config/nginx/vhost.d:/etc/nginx/vhost.d"
```

Would this still results in random volumes being created?

**Comment by buchdag** [comment]
Nope, if you use a bind mount Docker won't create a Docker volume.

**Comment by betomassoni** [comment]
Even using named container this is returning the error to me.

```
nginx-proxy-letsencrypt | [Mon Feb  1 12:30:50 UTC 2021] Create new order error. Le_OrderFinalize not found. {
nginx-proxy-letsencrypt |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx-proxy-letsencrypt |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: mydomain.com: see https://letsencrypt.org/docs/rate-limits/",
nginx-proxy-letsencrypt |   "status": 429
nginx-proxy-letsencrypt | }
nginx-proxy-letsencrypt | [Mon Feb  1 12:30:50 UTC 2021] Please check log file for more details: /dev/null
nginx-proxy-letsencrypt | Sleep for 3600s
```

My docker-compose:

```
version: '3'
services:

  app:
    build:
        dockerfile: ./app-java.dockerfile
        context: .
    image: robertomassoni/java-app-test 
    restart: always   
    expose:
      - "8080"
    ports: 
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=mydomain.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=email@email.com 
    networks: 
      - web 

  nginx-proxy:
    container_name: 'nginx-proxy'
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx-proxy"        
    networks: 
      - web
    ports: 
      - "80:80"
      - "443:443"

  nginx-letsencrypt:
    container_name: 'nginx-proxy-letsencrypt'
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: 
      - web

networks:
  web:
    external: true

volumes:
  certs:
  html:
  vhost:
```

**Comment by buchdag** [comment]
> **Required read if you use the `latest` version** : the recent `v2.0.0` release of this project mark the switch of the ACME client used by the Docker image from [**simp.le**](https://github.com/zenhack/simp_le) to [**acme.sh**](https://github.com/acmesh-official/acme.sh). This switch result in some backward incompatible changes, so please read [this issue](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/510) and the updated docs for more details before updating your image. The single most important change is that the container now requires a volume mounted to `/etc/acme.sh` in order to persist ACME account keys and SSL certificates. The last tagged version that uses **simp_le** is `v1.13.1`.

**Comment by betomassoni** [comment]
Thank you @buchdag!!


Could you give an example? I tested the code below on a **new** host but the same error appeared. Should I wait a week?

```
version: '3'
services:

   [...]

  nginx-proxy:
    container_name: 'nginx-proxy'
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - acme:/etc/acme.sh
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx-proxy"        
    networks: 
      - web
    ports: 
      - "80:80"
      - "443:443"

  nginx-letsencrypt:
    container_name: 'nginx-proxy-letsencrypt'
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: 
      - web 

networks:
  web:
    external: true

volumes:
  certs:
  html:
  vhost:
  acme:
```
