### ISSUE TITLE
javax.net.ssl.SSLException: hostname in certificate didn't match:

### ISSUE THREAD

**Issue by Rocks360** [JrCs/docker-letsencrypt-nginx-proxy-companion#224]
Hello I setup artifacroty in a container like below
```
version: '2'

volumes: 
    artifactory_data:
    artifactory_logs:
    artifactory_backup:

services:
    artifactory:
        image: mattgruter/artifactory
        container_name: artifactory-maven-repo
        hostname: artifactoryhost
        domainname: repositorys.example.com
        volumes:
            - artifactory_data:/artifactory/data
            - artifactory_logs:/artifactory/logs
            - artifactory_backup:/artifactory/backups
        environment:
            - VIRTUAL_HOST=repositorys.example.com,www.repositroys.example.com
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=repositorys.example.com,www.repositroys.example.com
            - LETSENCRYPT_EMAIL=myemail@test.de

networks:
  default:
    external:
      name: frontend-network
```

I also have some other services with an similar script up and running. All subdomain  services are reachable but when I try to get publish a repository to my artifactory service, gradle gives me the following error:

`javax.net.ssl.SSLException: hostname in certificate didn't match: <www.sub.domain.online> != <www.sub1.domain.online> OR <www.sub2.domain.online> OR <www.sub3.domain.online>`
