### ISSUE TITLE
"SEC_ERROR_UNKNOWN_ISSUER"

### ISSUE THREAD

**Issue by DuncanBetts** [JrCs/docker-letsencrypt-nginx-proxy-companion#225]
Hi

Any idea where I've gone wrong?

Here's the log from the session where the certificate was issued:

```
Attaching to gunicorn, nginx, nginx-letsencrypt, docker-gen
gunicorn             | [2017-06-29 14:23:07 +0000] [1] [INFO] Starting gunicorn 19.7.1
gunicorn             | [2017-06-29 14:23:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
gunicorn             | [2017-06-29 14:23:07 +0000] [1] [INFO] Using worker: eventlet
gunicorn             | [2017-06-29 14:23:07 +0000] [7] [INFO] Booting worker with pid: 7
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container docker-gen)...
nginx-letsencrypt    | Creating/renewal qr.whichbonus.win certificates... (qr.whichbonus.win)
nginx-letsencrypt    | 2017/06/29 14:23:09 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
nginx-letsencrypt    | 2017/06/29 14:23:09 Watching docker events
nginx-letsencrypt    | 2017/06/29 14:23:09 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
docker-gen           | 2017/06/29 14:23:09 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
docker-gen           | 2017/06/29 14:23:09 Sending container 'nginx' signal '1'
docker-gen           | 2017/06/29 14:23:09 Watching docker events
docker-gen           | 2017/06/29 14:23:09 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | 2017-06-29 14:23:09,896:INFO:simp_le:1211: Generating new account key
nginx-letsencrypt    | 2017-06-29 14:23:11,206:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
nginx-letsencrypt    | 2017-06-29 14:23:11,824:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
nginx-letsencrypt    | 2017-06-29 14:23:13,576:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): qr.whichbonus.win
nginx                | qr.whichbonus.win 172.18.0.1 - - [29/Jun/2017:14:23:13 +0000] "GET /.well-known/acme-challenge/0jl__OXYnWGBL4gptWf_AN5IEIHEEqeiq95i5i-P920 HTTP/1.1" 200 87 "-" "python-requests/2.8.1"
nginx-letsencrypt    | 2017-06-29 14:23:13,594:INFO:simp_le:1305: qr.whichbonus.win was successfully self-verified
nginx-letsencrypt    | 2017-06-29 14:23:13,814:INFO:simp_le:1313: Generating new certificate private key
nginx                | qr.whichbonus.win 66.133.109.36 - - [29/Jun/2017:14:23:13 +0000] "GET /.well-known/acme-challenge/0jl__OXYnWGBL4gptWf_AN5IEIHEEqeiq95i5i-P920 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-letsencrypt    | 2017-06-29 14:23:14,769:INFO:simp_le:391: Saving account_key.json
nginx-letsencrypt    | 2017-06-29 14:23:14,770:INFO:simp_le:391: Saving key.pem
nginx-letsencrypt    | 2017-06-29 14:23:14,771:INFO:simp_le:391: Saving chain.pem
nginx-letsencrypt    | 2017-06-29 14:23:14,771:INFO:simp_le:391: Saving fullchain.pem
nginx-letsencrypt    | 2017-06-29 14:23:14,772:INFO:simp_le:391: Saving cert.pem
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container docker-gen)...
nginx-letsencrypt    | Sleep for 3600s
nginx                | qr.whichbonus.win 89.172.183.245 - - [29/Jun/2017:14:23:33 +0000] "GET / HTTP/1.1" 200 12 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

The contents of the folder on the local machine that contains the saved files:

```
root@localhost:/app/volumes/nginx/certs# ls -l
total 8
-rw-r--r-- 1 root root  424 Jun 27 12:44 dhparam.pem
drwxr-xr-x 2 root root 4096 Jun 29 14:23 qr.whichbonus.win
lrwxrwxrwx 1 root root   29 Jun 29 14:23 qr.whichbonus.win.chain.pem -> ./qr.whichbonus.win/chain.pem
lrwxrwxrwx 1 root root   33 Jun 29 14:23 qr.whichbonus.win.crt -> ./qr.whichbonus.win/fullchain.pem
lrwxrwxrwx 1 root root   13 Jun 29 14:23 qr.whichbonus.win.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   27 Jun 29 14:23 qr.whichbonus.win.key -> ./qr.whichbonus.win/key.pem
```

Note that this is a test server which I am sshing into as root, since it only contains a plain "hello world" flask app.

docker-compose.yaml

```
version: '2'

services:
  gunicorn:
    build: .
    restart: always
    container_name: gunicorn
    command: >
      gunicorn
      --bind 0.0.0.0:80
      --worker-class eventlet
      --log-file=-
      flask_app.app:app
    volumes:
      - '.:/flask_app'
    expose:
        - '80'
    environment:
      - VIRTUAL_HOST=qr.whichbonus.win
      - LETSENCRYPT_HOST=qr.whichbonus.win
      - LETSENCRYPT_EMAIL=my@emailaddress.com
      - LETSENCRYPT_TEST=true

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/nginx/certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
```

Using Firefox 54 I get "SEC_ERROR_UNKNOWN_ISSUER" advising me not to continue to the page itself, and using the latest Opera on a different machine the page loads but clicking a globe to the left of the domain name reveals a dropdown informing me the issuer of the SSL certificate is not trusted.

I've been trying to solve this, I've ran `docker-compose down` and `docker-compose up --build` since the certificate was issued.
