### ISSUE TITLE
Connection refused on 443

### ISSUE THREAD

**Issue by martinhpunkt** [JrCs/docker-letsencrypt-nginx-proxy-companion#241]
Hi all,

tried my best for the last two days and do not get the clue. Hopefully I haven't made any basic mistakes which I should have identified myself, however, if you could provide me assistance I'd be thankful.

My desired setup is as follows:
1) one nginx proxy serving for all services as reverse proxy
2) letsencrypt support with this project
3) one separate container for each service

My current design approach is to have separated docker compose files. The first defines the first two requirements and for each container from 3) there will be a separate compose file.

My compose file for nginx and nginx-companion looks like this:

```
version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            DEFAULT_HOST: domain.com
            DOCKER_HOST: unix:///tmp/docker.sock
        volumes:
            - certs:/etc/nginx/certs:ro
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /root/docker-setup/nginx-letsencrypt/sync.domain.com.conf:/etc/nginx/vhost.d/sync.domain.com
        networks:
            - nw
    proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: proxy-companion
        environment:
            - DEBUG=true
        volumes:
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
            - proxy
        networks:
            - nw
volumes:
    certs:
    vhost.d:
    html:
networks:
    nw:
```

I added an additional configuration file to overcome [Issue #254](https://github.com/jwilder/nginx-proxy/pull/254) from jwilder's project, i.e. I want to have multiple containers running on one subdomain.

The content of the additional file is very simple:
```
location /owncloud/ {
        proxy_pass http://sync.domain.com/owncloud/;
}
```

Which finally leads to the compose file of 3) which is owncloud:
```
version: '2'
services:
    mariadb:
        image: mariadb:latest
        container_name: owncloud-mariadb
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/tmp/initpw/mariadbpw-root
            - MYSQL_DATABASE=ocdb
            - MYSQL_USER=ocuser
            - MYSQL_PASSWORD_FILE=/tmp/initpw/mariadbpw-ocuser
        volumes:
            - /root/docker-setup/owncloud/:/tmp/initpw/
            - volume-owncloud-mariadb:/var/lib/mysql
            - /root/docker-setup/owncloud/init-data:/docker-entrypoint-initdb.d/
        networks:
            nw_owncloud:
    owncloud:
        image: owncloud:9.1
        container_name: owncloud
        environment:
            - VIRTUAL_HOST=sync.domain.com
#            - VIRTUAL_PATH="/owncloud/"
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=sync.domain.com
            - LETSENCRYPT_EMAIL=webmaster@domain.com
            - LETSENCRYPT_TEST=true
#        ports:
#            - 8180:80
        expose:
            - 80
        volumes:
            - /ocdata:/var/www/html
        networks:
            nw_owncloud:
volumes:
    volume-owncloud-mariadb:
#        external: true
networks:
    nw_owncloud:
#         external: true
```
Here comes the issue. The owncloud container with http and the ip works well so I can assume that this setup is working. When it comes to nginx and nginx-companion I don't even get log messages from nginx-proxy.

Example:
```
curl -v --ipv4 -I https://sync.domain.com/owncloud
*   Trying XXX.XXX.141.136...
* connect to XXX.XXX.141.136 port 443 failed: Verbindungsaufbau abgelehnt
* Failed to connect to sync.domain.com port 443: Verbindungsaufbau abgelehnt
* Closing connection 0
curl: (7) Failed to connect to sync.domain.com port 443: Verbindungsaufbau abgelehnt`
```
(translated: connection refused).

What I tried/verified
- the certificates are there
- iptables do not seem to me as if there was something wrong
- curl with normal http works and I'm getting logs
- [issue317](https://github.com/jwilder/nginx-proxy/issues/317) from jwilders did not work either, I even tried to "compose" the containers on the command line.

Do you _please_ have any hint I can follow? Any help would be appreciated!

Kind regards,
Martin
