### ISSUE TITLE
Access SSL service through VPN and nginx reverse proxy

### ISSUE THREAD

**Issue by hugohil** [JrCs/docker-letsencrypt-nginx-proxy-companion#250]
Hi :)

First of all, sorry if I'm asking anything obvious, I'm fairly new to the Docker ecosystem. I've already posted a [question](https://stackoverflow.com/questions/45816822/access-docker-service-with-https-through-vpn-and-nginx-reverse-proxy) on SO, but hadn't any luck.

My issue is:

I have a wordpress site that I want to access only behind my VPN, and through https protocol.

With the `docker-compose.yml` file thereafter, I get to connect to openvpn, and access my wordpress site through `http://172.200.0.11/`, but **not** `https://172.200.0.11/`, nor `http://example.com` or `https://example.com`. Server is Digital Ocean droplet, which I added an A record for `example.com` pointing to `172.200.0.11` and a CNAME that's an alias for `example.com`. `nginx-gen` template is https://github.com/jwilder/docker-gen/blob/master/templates/nginx.tmpl.

`docker-compose.yml`:
```yml
version: "2"

services:
  openvpn:
    cap_add:
      - "NET_ADMIN"
    image: "kylemanna/openvpn"
    container_name: "openvpn"
    ports:
      - "1194:1194/udp"
    restart: "always"
    volumes:
      - "./volumes/openvpn-data/conf:/etc/openvpn"
    networks:
      private:
        ipv4_address: 172.200.0.10

  nginx:
    restart: "always"
    image: "nginx"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "./volumes/www/wordpress:/usr/share/nginx/html"
      - "./volumes/certs:/etc/nginx/certs:ro"
    networks:
      proxy:

  nginx-gen:
    restart: "always"
    image: "jwilder/docker-gen"
    container_name: "nginx-gen"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - "nginx"
    entrypoint: "/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

  letsencrypt-nginx-proxy-companion:
    restart: "always"
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "letsencrypt-nginx-proxy-companion"
    volumes_from:
      - "nginx"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    networks:
      proxy:

  mysql:
    image: "mariadb"
    restart: "always"
    volumes:
      - "./volumes/var/mysql:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      private:
        ipv4_address: 172.200.0.12

  wordpress:
    image: "wordpress"
    restart: "always"
    hostname: "example.com"
    links:
      - "mysql"
    ports:
      - "8080:80"
    volumes:
      - "./volumes/www/wordpress:/var/www/html"
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=mail@provider.net
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_NAME=myapp
      - WORDPRESS_DB_PASSWORD=password
    networks:
      proxy:
      private:
        ipv4_address: 172.200.0.11

networks:
  private:
    ipam:
      config:
        - subnet: 172.200.0.0/16
  proxy:
```

I'm not entirely sure wether the issue is on letsencrypt, openvpn or nginx side (cc @kylemanna @jwilder), though I would suggest it is letsencrypt side. Might also be my `docker-compose` skills ...

Any help would be greatly appreciated :)
