### ISSUE TITLE
Should nginx be reloaded after a certificat has been renewed?

### ISSUE THREAD

**Issue by victor-lund** [JrCs/docker-letsencrypt-nginx-proxy-companion#265]
Hello,

I am using a docker setup with the following images:

- nginx
- jwilder/docker-gen
- jrcs/letsencrypt-nginx-proxy-companion

...and I'm facing issues with renewed certificates. I believe that my certificates are getting renewed properly but I don't think nginx is restarted when a certificat has been renewed.

**When using a non-docker setup**, I would typically use certbot together with a cron job that looks something like this:

`30 2 * * * /usr/bin/certbot renew --noninteractive --renew-hook "/bin/systemctl reload nginx" >> /var/log/le-renew.log
`

...which reloads nginx when a certificate has been renewed.

I suspect that this functionality either isn't implemented in my setup or alternatively that it is not working properly.

Anyone out there having similar experiences or ideas how I could track down what is causing my certificates / nginx issues?

**Comment by buchdag** [comment]
Are you using a recent enough version of `jrcs/letsencrypt-nginx-proxy-companion` ?

#199 was a similar issue fixed by #165 on May, 28.

**Comment by MichaelBorde** [comment]
Latest release (1.5) seems to be on May, 18. Do you suggest we use lastest tag when pulling your image ?

**Comment by buchdag** [comment]
Yes, better use `latest`, the project maintainer seems to be very busy and only shows up once in a while to merge some simple PRs.

**Comment by victor-lund** [comment]
I do use the :latest tag, and the image i'm using was created in september 2017.

I can confirm that the certificates are getting updated properly but that the nginx service is not reloaded as it needs to be after a certificate has been renewed. Im surprised that not everyone is encountering this issue...

**Comment by buchdag** [comment]
Are you sure all your containers are properly setup with the right labels or env variable ?

**Comment by victor-lund** [comment]
@buchdag Well, Everything is working except for the nginx service not reloading. I can't swear on the fact that all settings are properly made. Which variables are needed to restart nginx after a certificate has been successfully renewed?

**Comment by buchdag** [comment]
Preferably the `com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy` label set on the `nginx` / `nginx-proxy` container or alternatively if your `nginx` / `nginx-proxy` container has a static name, the `NGINX_PROXY_CONTAINER` env variable set to this name on the `letsencrypt-nginx-proxy-companion` container.

**Comment by buchdag** [comment]
I just forced the renewal of one of my certificate from inside the `letsencrypt-nginx-proxy-companion`, the `nginx` container was correctly restarted as stated by the last line:

```
Creating/renewal app.example.com certificates... (app.example.com )
2017-11-01 14:19:51,658:INFO:simp_le:1306: app.example.com was successfully self-verified
2017-11-01 14:19:51,879:INFO:simp_le:1314: Generating new certificate private key
2017-11-01 14:19:53,500:INFO:simp_le:393: Saving key.pem
2017-11-01 14:19:53,504:INFO:simp_le:393: Saving fullchain.pem
2017-11-01 14:19:53,505:INFO:simp_le:393: Saving cert.pem
Reloading nginx docker-gen (using separate container 7dd2fcadc5e2756e070e9f2688611419870c8c663eccf4f17f269e12779d89e6)...
Reloading nginx (using separate container 39cb4f97bfc0f723260fdd0d427f20ab72ab3887be7dd3a889187be013195942)...
```

And it served the renewed certificate for this webapp (expiring on january 30 2018), so I confirm that with a correctly configured stack renewal work as it should.

**Comment by jasonchi38** [comment]
buchdag, can you post your working compose stack file examples? thanks in advance.

**Comment by victor-lund** [comment]
@buchdag Can you clearify how you forced the renewal of a given certificate? I've been looking for this feature before with no success.

I'd also like to see a working compose stack file example, as requesten by @jasonchi38

**Comment by buchdag** [comment]
Okay, turns out there seems to be an issue with the `com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy` label on a test VM that I never encountered on my production VMs. Suspected an issue with the docker version but both are current (either 17.09 or 17.10), so no idea where it comes from. I'll have a look into this.

Here is a working compose stack for nginx-proxy + letsencrypt. Just remember that you have to manually create the `nginx-proxy` network before starting the compose stack with `docker network create nginx-proxy`.

```
version: '3'

services:
  nginx:
    image: nginx:1.13.5-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  dockergen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external: 
      name: nginx-proxy
```

Pining the version of `nginx` and `docker-gen` is not required, that's just my habit with compose stacks.

And an example proxyed app (a simple nginx serving static content):

```
version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./www:/usr/share/nginx/html:ro
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: nginxproxyle.duuu.ch
      LETSENCRYPT_HOST: nginxproxyle.duuu.ch
      LETSENCRYPT_EMAIL: whatever@email.tld

networks:
  default:
    external:
      name: nginx-proxy
```

You can access it at https://nginxproxyle.duuu.ch, there is nothing else running on this vm than those two docker compose files.

First cert generated at container launch: https://storage.googleapis.com/dl.duuu.ch/cert1.png

Forced a renewal, refreshed the page, renewed certificate is correctly served by nginx: https://storage.googleapis.com/dl.duuu.ch/cert2.png

(sorry for the french UI)

> Can you clearify how you forced the renewal of a given certificate? I've been looking for this feature before with no success.

`docker exec NAME_OF_YOUR_LE_CONTAINER /app/force_renew` but turns out there is an issue with that too and it's only renewing the first domain it finds, not all of them as it should. I'm the one who added this feature so I'll have a look at it immediately.

**Comment by victor-lund** [comment]
@buchdag thanks for your very detailed answers! I will take a closer look later this week and investigate if they solve my problems. Please let me know when the force renew works as expected - this is principally a very handy feature.

**Comment by buchdag** [comment]
I'm pretty sure I already know why it does not work as intended, very basic and stupid mistake on my behalf.

**Comment by buchdag** [comment]
@victor-lund > the fix was just merged, if you pull `jrcs/letsencrypt-nginx-proxy-companion:latest` it should correctly force renewal of all existing certificates when you execute the `/app/force_renew` script.

**Comment by g2gdeploy** [comment]
Hi @buchdag, I tried it with the latest version but doesn't seem to work for me.

Steps to reproduce;

1. run docker-compose up  (see below)
2. `docker exec nginx-letsencrypt /app/force_renew`

This is the output of the second command.
```
Creating/renewal some.domain.com certificates... (some.domain.com)
2017-11-17 13:05:48,527:INFO:simp_le:1306: some.domain.com was successfully self-verified
2017-11-17 13:05:48,739:INFO:simp_le:1314: Generating new certificate private key
2017-11-17 13:05:50,196:INFO:simp_le:393: Saving key.pem
2017-11-17 13:05:50,197:INFO:simp_le:393: Saving fullchain.pem
2017-11-17 13:05:50,197:INFO:simp_le:393: Saving cert.pem
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx-proxy)...
```

Although everything seems to be OK the nginx-proxy container is not being restarted.


This is my setup with docker-compose;

```
version: '3'

services:

  nginx-proxy:
    image: nginx:1.13
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-gen
    restart: always
    # Use entrypoint as workaround for bug: https://github.com/jwilder/docker-gen/issues/201#issuecomment-227990877
    entrypoint: /bin/sh -c
    command: ['/usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf']
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
      # set this hash manually as workaround for bug: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277#issuecomment-344612875
      ACME_TOS_HASH: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b

  nginx-hello-world:
    image: karthequian/helloworld:latest
    container_name: nginx-hello-world
    restart: always
    environment:
      VIRTUAL_HOST: some.domain.com
      LETSENCRYPT_HOST: some.domain.com
      LETSENCRYPT_EMAIL: some@domain.com

volumes:
  nginx-conf:
  nginx-vhosts:
  nginx-html:
  nginx-certs:

networks:
  default:
    external:
      name: playground-network
```
