### ISSUE TITLE
nginx-letsencrypt    | 2017-10-28 16:57:45,016:WARNING:simp_le:1304: xxx.domain.com was not successfully self-verified. CA is likely to fail as well!

### ISSUE THREAD

**Issue by Telokis** [JrCs/docker-letsencrypt-nginx-proxy-companion#269]
I keep having this exact issue with one specific container I am trying to make.

Here is the nginx docker-compose file:

```yml
version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    environment:
      VIRTUAL_PROTO: "https"
      DEFAULT_HOST: "mydefaulthost.com"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_FILES_PATH}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

networks:
  default:
    external:
      name: nginx
```

Then I have this docker-compose file working perfectly:

```yml
version: '3'

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./data/torrents:/downloads
      - ./data/watch:/watch
      - ./data/config:/config
    environment:
      VIRTUAL_HOST: "host.domain.com"
      VIRTUAL_PORT: 9091
      LETSENCRYPT_HOST: "host.domain.com"
      LETSENCRYPT_EMAIL: "myemail"

networks:
  default:
    external:
      name: nginx
```

And, finally, the one that doesn't work at all:

```yml
version: '3'

services:
  rtfm:
    container_name: rtfm
    image: rtfm
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      VIRTUAL_HOST: "host2.domain.com"
      LETSENCRYPT_HOST: "host2.domain.com"
      LETSENCRYPT_EMAIL: "myemail"

networks:
  default:
    external:
      name: nginx
```

The Dockerfile of this image exposes PORT 80.

If I run my container directly (`docker run -i -p 80:80 rtfm`) it works perfectly.

My nginx docker-compose file was taken/inspired from https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

**Comment by Telokis** [comment]
I'd like to add that both of my containers are meant to be accessed from subdomains of my domain. I tried setting `LETSENCRYPT_HOST` to my domain ignoring the subdomains but it didnt work either.

**Comment by buchdag** [comment]
Does the letsencrypt container correctly generate your certificates anyway ?

The self verification is not reliable and have been discarded from the next version of simp_le.

**Comment by Telokis** [comment]
I don't think it does, how do I know?
When I try to access my site I get an error from chrome saying this website is not secure. (It works fine for transmission though)
Even strangier, if I tell chrome to process anyway I notice that the vhost for my second website points in fact to transmission!

So host2.domain.com points to host.domain.com but without https... I don't understand at all!

**Comment by buchdag** [comment]
Looks like your nginx container don't even get a correct proxy configuration from docker-gen.

Have you tried adding an explicit `VIRTUAL_PORT: 80` on the non working container ?

Are you using the latest versions of `jrcs/letsencrypt-nginx-proxy-companion` and [nginx.tmpl](https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl) ?

Adding `DEBUG: "true"` to your `nginx-letsencrypt` container will give you more verbose logs.

**Comment by Telokis** [comment]
```
$ docker-compose up
Recreating nginx-letsencrypt ... 
Recreating nginx-letsencrypt
Starting nginx ... 
Starting nginx
Starting nginx-gen ... 
Recreating nginx-letsencrypt ... done
Attaching to nginx, nginx-gen, nginx-letsencrypt
nginx-gen            | 2017/11/02 09:29:10 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-gen            | 2017/11/02 09:29:10 Watching docker events
nginx-letsencrypt    | Sleep for 3600s
nginx-gen            | 2017/11/02 09:29:10 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | 2017/11/02 09:29:10 Generated '/app/letsencrypt_service_data' from 2 containers
nginx-letsencrypt    | 2017/11/02 09:29:10 Running '/app/update_certs'
nginx-letsencrypt    | 2017/11/02 09:29:10 Watching docker events
nginx-gen            | 2017/11/02 09:29:10 Received signal: hangup
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container nginx-gen)...
nginx-gen            | 2017/11/02 09:29:10 Received signal: hangup
nginx-letsencrypt    | Reloading nginx (using separate container nginx)...
nginx-gen            | 2017/11/02 09:29:10 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | Creating/renewal mydomain.com certificates... (mydomain.com  rtfm.mydomain.com)
nginx-letsencrypt    | 2017/11/02 09:29:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
nginx-letsencrypt    | 2017-11-02 09:29:10,560:INFO:simp_le:1213: Generating new account key
nginx-letsencrypt    | 2017-11-02 09:29:13,518:ERROR:acme.challenges:311: Unable to reach http://rtfm.mydomain.com/.well-known/acme-challenge/qp-Mexz7a6ir5p3TTBA8X-JdIl8y5H7Ypoz0AWGWYfA: ('Connection aborted.', error(104, 'Connection reset by peer'))
nginx-letsencrypt    | 2017-11-02 09:29:13,518:WARNING:simp_le:1304: rtfm.mydomain.com was not successfully self-verified. CA is likely to fail as well!
nginx-letsencrypt    | 2017-11-02 09:29:13,758:ERROR:acme.challenges:311: Unable to reach http://mydomain.com/.well-known/acme-challenge/BcfNme8jZRbIcWjDX69PDI1j9JqwUJO-jTnCUBI9rGg: ('Connection aborted.', error(104, 'Connection reset by peer'))
nginx-letsencrypt    | 2017-11-02 09:29:13,758:WARNING:simp_le:1304: mydomain.com was not successfully self-verified. CA is likely to fail as well!
nginx-letsencrypt    | 2017-11-02 09:29:14,005:INFO:simp_le:1314: Generating new certificate private key
nginx-letsencrypt    | 2017-11-02 09:29:14,810:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-staging.api.letsencrypt.org/acme/authz/O-YzfQbv74efzYFftT5AxeJmTkjJf4OfHVSK02eXit0, https://acme-staging.api.letsencrypt.org/acme/authz/_zGn7_PQtU03hCQ7uHgHd7_YVO2waU3ArGVZP0H6-I4
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    | 
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | Sleep for 3600s
```

I don't get it, nothing works at all.

Here is a recap of my current docker-compose.yml files:

The one containing nginx stuff

```
version: '3'
services:
  nginx:
    image: nginx:latest
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    environment:
      VIRTUAL_PROTO: "https"
      DEFAULT_HOST: "mydomain.com"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_FILES_PATH}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

networks:
  default:
    external:
      name: nginx
```

The one for my app:

```
version: '3'

services:
  rtfm:
    container_name: rtfm
    image: rtfm
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      DEBUG: "true"
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: "rtfm.mydomain.com"
      LETSENCRYPT_HOST: "mydomain.com, rtfm.mydomain.com" # I tried lots of things here
      LETSENCRYPT_EMAIL: "myemail@foo.bar"      
      
networks:
  default:
    external:
      name: nginx
```

I switched to test mode because let's encrypt wasn't happy of all my attempts.

**Comment by buchdag** [comment]
`DEBUG: "true"` goes to the `jrcs/letsencrypt-nginx-proxy-companion` container, not the proxyed one.

You should remove `VIRTUAL_PROTO` and `DEFAULT_HOST`, adding optional stuff certainly won't help troubleshooting.

As you use the `NGINX_PROXY_CONTAINER` on the letsencrypt container with a fixed nginx container name, the label on the nginx container isn't needed, but that probably is of no consequence.

Are you sure your `mydomain.com` and `rtfm.mydomain.com` A records point to this host ? Do you have AAAA records on this domain and its subdomain ?

**Comment by buchdag** [comment]
The log shows that your nginx container is not even receiving the GET request from the Letsencrypt servers, you definitely have a DNS or network issue somewhere.

**Comment by Telokis** [comment]
Alright, I tried some things.

First of all, I had a firewall that I disabled.
I tried using nginx-proxy alone, without SSL and it worked.
I removed docker-gen and now use nginx-proxy alone.

Here is the new docker-compose.yml file:
```yml
version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
      DEBUG: "true"
      NGINX_PROXY_CONTAINER: "nginx-proxy"
```

And here is the full log of docker-compose up: https://pastebin.com/MCXURRL4

As a reminder, the docker-compose.yml of my app:
```yml
networks:
  default:
    external:
      name: nginx

version: '3'

services:
  rtfm:
    container_name: rtfm
    image: rtfm
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: "rtfm.mydomain.com"
      LETSENCRYPT_HOST: "rtfm.mydomain.com"
      LETSENCRYPT_EMAIL: "myemail@foo.bar"      
      
networks:
  default:
    external:
      name: nginx
```

Now, it's better but when I go to `https://rtfm.mydomain.com`, chrome warns me that the website is not secured. (HTTPS in red)
