### ISSUE TITLE
ERROR:simp_le:1272: CA marked some of the authorizations as invalid [...]

### ISSUE THREAD

**Issue by TheLux83** [JrCs/docker-letsencrypt-nginx-proxy-companion#283]
Hey there,

I'm trying to get this companion running since a few days/weeks. I've had a few problems but I'm getting nearer and nearer on successing. But now I'm at the end für my knowledge-road.

I've set up the nginx-proxy, docker-gen and this companion and everything seems to work just fine. At least when I' not using this companion.
When I try to get a new SSL Certificate, I get the following error message:

```
nginx-letsencrypt    | 2017/11/17 09:32:46 Received event start for container 9ed4a9635a04
docker-gen           | 2017/11/17 09:32:46 Received event start for container 9ed4a9635a04
docker-gen           | 2017/11/17 09:32:46 Generated '/etc/nginx/conf.d/default.conf' from 11 containers
docker-gen           | 2017/11/17 09:32:46 Sending container 'nginx-proxy' signal '1'
nginx-letsencrypt    | 2017/11/17 09:33:01 Debounce minTimer fired
nginx-letsencrypt    | 2017/11/17 09:33:01 Generated '/app/letsencrypt_service_data' from 9 containers
nginx-letsencrypt    | 2017/11/17 09:33:01 Running '/app/update_certs'
nginx-letsencrypt    | Creating/renewal domain.tld certificates... (domain.tld sub.domain.tld)
nginx-letsencrypt    | 2017-11-17 09:33:02,224:INFO:simp_le:1213: Generating new account key
nginx-proxy          | sub.domain.tld 172.17.0.1 - - [17/Nov/2017:09:33:06 +0000] "GET /.well-known/acme-challenge/tMZuivnTE_5-9R9KsaXMfgtTNztQe888ydZAj8FvaZU HTTP/1.1" 200
87 "-" "python-requests/2.18.4"
nginx-letsencrypt    | 2017-11-17 09:33:06,454:INFO:simp_le:1306: sub.domain.tld was successfully self-verified
nginx-letsencrypt    | 2017-11-17 09:33:07,113:WARNING:simp_le:1304: domain.tld was not successfully self-verified. CA is likely to fail as well!
nginx-proxy          | sub.domain.tld 172.17.0.1 - - [17/Nov/2017:09:33:07 +0000] "GET /.well-known/acme-challenge/tMZuivnTE_5-9R9KsaXMfgtTNztQe888ydZAj8FvaZU HTTP/1.1" 200
87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-letsencrypt    | 2017-11-17 09:33:07,683:INFO:simp_le:1314: Generating new certificate private key
nginx-letsencrypt    | 2017-11-17 09:33:08,754:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-
known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains a
ccessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/Nlnr4bDUZihIGiLZJ67hxSx6WoFdZKTUvzY4wkPfsB4
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    |
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | Sleep for 3600s
```

I think it has something to do with my attempt to use a SAN-Certificate. I was trying to use them, because I was running against the limit when I tried several things.

My nginx-proxy comose file looks like this:
```
version: '2'

services:
  nginx-proxy:
    image: nginx
    network_mode: "bridge"
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_proxy_conf.d:/etc/nginx/conf.d
      - nginx_proxy_vhost.d:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
      - nginx_proxy_certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  docker-gen:
    image: jwilder/docker-gen
    network_mode: "bridge"
    container_name: docker-gen
    volumes_from: 
    - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - D:/Docker/nginx-proxy:/etc/docker-gen/templates
    links:
      - nginx-proxy
    command: "-notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    network_mode: "bridge"
    container_name: nginx-letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_proxy_certs:/etc/nginx/certs:rw
    environment:
      - ACME_TOS_HASH=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
volumes:
  nginx_proxy_conf.d:
  nginx_proxy_vhost.d:
  nginx_proxy_html:
  nginx_proxy_certs: 
```
I'm using the actual ACME_TOS_HAS.
My compose file for my container looks like this:

```
version: '2'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    network_mode: "bridge"
    ports:
      - "8093:80"
    environment:
      - VIRTUAL_HOST=domain.tld,sub.domain.tld
      - LETSENCRYPT_HOST=domain.tld,sub.domain.tld
      - LETSENCRYPT_EMAIL=name@emailaddress.com
    volumes:
      - nextclouddata:/var/www/html
    external_links:
      - mysql:mysql
volumes:
    nextclouddata:
```

I don't know what the problem is. I've forwarded the ports 80 and 443 to my server and it still doesn't work.
sub.domain.tld isn't the real URL but I don't think I have to say that, have I? :D

**Comment by buchdag** [comment]
What's that `D:/` on the second docker-gen volume ?

**Comment by TheLux83** [comment]
Hey @buchdag 
this is my shared windows volume where I save the newest nginx.tmpl every day.
I forogt to mention, that I work with Docker for Windows and the moby.linux VM.
But everythin else is using a docker volume, so this shouldn't be a big problem I think (and hope.)

**Comment by buchdag** [comment]
First try starting your `nginx-proxy` stack from scratch:

```
docker-compose down -v
docker-compose up
```

This will delete then re-create the volumes declared in the compose file in addition to the containers:
```
  nginx_proxy_conf.d:
  nginx_proxy_vhost.d:
  nginx_proxy_html:
  nginx_proxy_certs:
```

That won't touch `D:/`

Then when the letsencrypt container is ready, try starting nextcloud again.
