### ISSUE TITLE
Force not to set http

### ISSUE THREAD

**Issue by zvinger** [JrCs/docker-letsencrypt-nginx-proxy-companion#293]
I had 3 services:

With HTTPS:
service.com
api.service.com

No HTTPS (testing and etc):
phpmyadmin.service.com
docs.service.com
something.service.com

Https work perfect, but nginx-proxy redirects to https non-https services (phpmyadmin and etc). But I didn't defined LETSENCRYPT_HOST in phpmyadmin, docs, something. What should I do to force use http on these services?

Thank you!

**Comment by buchdag** [comment]
@zvinger > remove the symlinks inside `/etc/nginx/certs` to the key and certificate for the subdomains you don't want https turned on, then restart the nginx container. This will disable https for those subdomains.

Example : for the subdomain `phpmyadmin.service.com`, remove

- `/etc/nginx/certs/phpmyadmin.service.com.crt`
- `/etc/nginx/certs/phpmyadmin.service.com.key`

Currently `letsencrypt-nginx-proxy-companion` does not have the logic needed to remove those symlinks when needed.

**Comment by zvinger** [comment]
There is no phpmyadmin.service.com.crt in /etc/nginx/certs folder. I see only service.com
api.service.com but in default.conf (nginx config) it tries to use service.com certificate

**Comment by buchdag** [comment]
Weird. If you use the latest upstream `nginx.tmpl`, SSL shouldn't be enabled at all [if you don't have both a `subdomain.crt` and `subdomain.key` files inside `/etc/nginx/certs/`](https://github.com/jwilder/nginx-proxy/blob/a6e8fae7f5959d1f7a4751f495d876ed174b612f/nginx.tmpl#L181).

Can you share your nginx-proxy config and the config of your service containers ? You can remove any personal information you don't want to share.

**Comment by zvinger** [comment]
```
docker run -d -p 80:80 -p 443:443 \
    --name nginx-proxy \
    --network reverse-proxy \
    --restart=always \
    -v $HOME/certs:/etc/nginx/certs:ro \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true \
    jwilder/nginx-proxy


docker run -d \
    --name nginx-letsencrypt \
    --restart=always \
    --volumes-from nginx-proxy \
    --network reverse-proxy \
    -v $HOME/certs:/etc/nginx/certs:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion

```

This is how I start nginx containers.

```
version: "2"
services:
  docs-production:
     image: service.com/api-doc
     networks:
       - reverse-proxy
     expose:
       - 80
     restart: always
     environment:
        - VIRTUAL_HOST=docs.service.com

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```
This is compose of docs.service.com

```
version: "2"
services:
  docs-production:
     image: service.com/app
     networks:
       - reverse-proxy
     expose:
       - 80
     restart: always
     environment:
        - VIRTUAL_HOST=service.com
        - LETSENCRYPT_EMAIL=email@email.email
        - LETSENCRYPT_HOST=service.com
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

```
This is compose of service.com

Thank you very much!
