### ISSUE TITLE
Use certificate for domain and subdomain

### ISSUE THREAD

**Issue by janus-reith** [JrCs/docker-letsencrypt-nginx-proxy-companion#294]
I have multiple apps running in one docker environment, and use nginx to route the main `example.com `to App 1, and `sub.example.com` to App 2.
While this works so far, the letsencrypt certificate is just valid for `sub.example.com.`

Im using this configuration in my docker-compose file:
```
environment:
      - VIRTUAL_HOST=sub.example.com
      - LETSENCRYPT_HOST=sub.example.com
      - LETSENCRYPT_EMAIL=mail@example.com
```

and for App 2:
```
environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=mail@example.com
```

**How to use the proxy companion to properly generate certs for both hosts?**

**Comment by janus-reith** [comment]
Ok, got it working now with the configuraton described above:

I had to manually inspect the docker volumes, and delete the whole certs there.
After restartign the containers, the certs are now generated properly.

But I think I'll still leave this open, as I don't consider this the proper solution.
When I add new containers to my docker environment, the lets encrypt companion should realize that certs are missing, instead of just using the ones already generated.

**Comment by buchdag** [comment]
> When I add new containers to my docker environment, the lets encrypt companion should realize that certs are missing

This is normally what it does. There was an issue in your case but I can't say what caused it with just the environment from the two proxyed apps.

**Comment by bcsjk11** [comment]
I am having an issue where I am creating containers using the same env as above, but just for docker run. The result is that it doesn't always (at random) create the right certs for the sub domains and therefore flags them as being invalid. 

In my docker run command I have the correct domain I want, but it is not the domain being used for the certs

**Comment by buchdag** [comment]
Hi.

What version of the container are you using ? Can you provide the full docker run commands you are using to start your nginx-proxy stack and your proxyed containers, and if possible the log output of the letsencrypt container when it issues a certificate with the wrong domain set ?

**Comment by bcsjk11** [comment]
It was a late night, but when I used the docker-compose rather than docker run commands it works. If it didn't work I could just recreate the `docker-letsencrypt-nginx-proxy-companion`.

Before I started on the docker-compose route, I did this:

```
docker run -d \
  --name nginx-proxy \
  -p 80:80 -p 443:443 \
  -v ${PWD}/certs:/etc/nginx/certs:ro \
  -v /etc/nginx/vhost.d \
  -v /usr/share/nginx/html \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  jwilder/nginx-proxy

docker run -d \
  --name nginx-letsencrypt \
  -v ${PWD}/certs:/etc/nginx/certs:rw \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --volumes-from nginx-proxy \
  jrcs/letsencrypt-nginx-proxy-companion

docker run -d \
  --name mainweb \
  --expose=80 --expose=443 \
  -p 80 -p 443 \
  -e "VIRTUAL_HOST=sub.my-domain" \
  -e "LETSENCRYPT_HOST=sub.my-domain" \
  -e "LETSENCRYPT_EMAIL=my-email@example.com" \
  -v ${PWD}/mainweb:/usr/local/apache2/htdocs \
  httpd:2.2.34-alpine
```

This would work, but the problems started to come up when I started adding more containers, not always (and this was random) giving the right certificate.

The main container that was giving me issues where the combo of a mysql and phpmyadmin container. Where the phpmyadmin wouldn't get a certificate.

```
docker run -di \
  --name wp-cite-mysql \
  -p 3310:3306 \
  -e MYSQL_ROOT_PASSWORD="(password123)" \
  -e MYSQL_USER="admin" \
  -e MYSQL_PASSWORD="(Admin123)**" \
  -v ${PWD}/cite-mysql-2018-s1:/var/lib/mysql \
  mysql:5.7.20

docker run -d  \
  -p 80 -p 443 \
  --link wp-cite-mysql \
  -e "VIRTUAL_HOST=pma1.my-domain" \
  -e "LETSENCRYPT_HOST=pma1.my-domain" \
  -e "LETSENCRYPT_EMAIL=my-email" \
  phpmyadmin/phpmyadmin
```

**Comment by buchdag** [comment]
You shouldn't try to publish ports 80 or 443 ports on the proxyed containers with the `-p` argument, just expose the 80 port (or whatever port your container is serving http over) with the `--expose` argument if it's not already exposed by the Dockerfile (they are most probably already exposed). If you try to reach http serving containers with directly published ports, that won't go through the proxy and the certificate won't be served.

The `--link` is a legacy argument dating back from when docker networks didn't exist, I know it's unfortunately still on a lot of containers docs but its usage should be avoided in favor of said docker networks.

To get the logs of the container, do `docker logs container-name`. If you'd prefer no to publicly post your domains and subdomains (they'll appear in the logs) you can send me the logs by mail.

Do you use the exact same config with docker compose ?

**Comment by bcsjk11** [comment]
Yeah - I do so I will look into it, the ports thing makes sense.
I will also look into using networks, but as you said a lot of containers (and explanations on the web) still use them.

Sorry if this didn't answer the origin post.

**Comment by buchdag** [comment]
> Sorry if this didn't answer the origin post.

No problem 😃

Also, If you have a working setup with docker-compose don't spend too much time trying to find why your first attempt with docker run did not work as intended. I'll give it a try with the same configuration as yours but I don't see any obvious reason for the proxy to randomly serve the wrong certificate.

**Comment by Markolie** [comment]
I seem to run into the exact same issue bcsjk11 is describing. I'm running a number of different subdomains with their own certificates, using largely the same setup bcsjk11 is using (except for using a separate nginx-proxy) network. All subdomains, such as jenkins.domain.com and api.domain.com work properly. 

However, the base domain (domain.com) appears to try to use the certificate of one of the subdomains, I believe the most recently generated one.

For instance, these two URL's work properly: https://jenkins.carely.info, https://jira.carely.info/secure/Dashboard.jspa
However, https://carely.info/ is trying to use the certificate belonging to jenkins.carely.info.

docker-compose.yml of one of the subdomains:
```
version: '3'

services:
  jira:
    image: cptactionhank/atlassian-jira-software
    container_name: jira
    expose:
      - "8080"
    volumes:
      - /var/atlassian/jira:/var/atlassian/jira
    environment:
      - VIRTUAL_HOST=${HOSTNAME}.${DOMAINNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
```

docker-compose.yml of the main domain:
```
version: '3'

services:
  pts4-application:
    build: .
    container_name: pts4-application
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DOMAINNAME}
      - LETSENCRYPT_HOST=${DOMAINNAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
```
