### ISSUE TITLE
Using in Docker Cloud gives `ERROR: you need to share your Docker host socket with a volume at /var/run/docker.sock`

### ISSUE THREAD

**Issue by laurenskling** [JrCs/docker-letsencrypt-nginx-proxy-companion#302]
When I use this package with docker-compose, it works, awesome.
When I try to use this in Docker Cloud, it keeps saying I need to add the volume `/var/run/docker.sock`. I tried to add it to this image and the `nginx-proxy` image endlessly but I cannot work out what is going wrong. Any help?

```
[letsencrypt-companion-1]2017-12-12T22:47:21.477087989Z ERROR: you need to share your Docker host socket with a volume at /var/run/docker.sock
[letsencrypt-companion-1]2017-12-12T22:47:21.477132361Z Typically you should run your container with: `-v /var/run/docker.sock:/var/run/docker.sock:ro`
[letsencrypt-companion-1]2017-12-12T22:47:21.477141639Z See the documentation at http://git.io/vZaGJ
```

my docker stack yml
```
letsencrypt-companion:
  image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
  links:
    - proxy
  volumes:
    - '/apps/web/ssl:/etc/nginx/certs'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
  volumes_from:
    - proxy
proxy:
  image: 'jwilder/nginx-proxy:latest'
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - '/apps/web/ssl:/etc/nginx/certs:ro'
mysite:
  image: ....
```
