### ISSUE TITLE
Can't automatic creat certificates

### ISSUE THREAD

**Issue by tldzyx** [JrCs/docker-letsencrypt-nginx-proxy-companion#309]
In my network, only 443 port can access. 

After me configure the container `jwilder/nginx-proxy` and the container 'letsencrypt-nginx-proxy-companion', I find it not work.

I read the log in 'letsencrypt-nginx-proxy-companion',  it's said
```
ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/3ieHUydG0E7wj25xdNg0j53OQsjfM0falMdtsPlgxXM'
```

The question looks like is the path `/.well-known/acme-challenge/X` can't access from http, and the nginx-proxy provider https not yet.

Before I use container, I use certbot in real system, and it work(I think it's use https in 443 port), but in this container, I don't know how to let it work, any one can help me?

**Comment by tldzyx** [comment]
> https://github.com/jwilder/nginx-proxy/issues/1010

**Comment by hoonoh** [comment]
I am having similar problems while doing server migration (just swapping to a bigger EC2 instance in AWS). First I noticed new certificate wasn't being issued for a new domain added with same error message above, so I tried restarting `nginx-letsencrypt` container with an empty `/etc/nginx/certs` directory which turned out no new certificates ever got re-issued. I tried this with old and new instance with the same dataset.

**Comment by buchdag** [comment]
@tldzyx > by _"In my network, only 443 port can access."_, do you mean you have no way of using port 80 ? 

If so you won't be able to use this project at all, the ACME client used (`simp_le`) only support `http-01` challenge, which require a working port 80 connection. There is no way to bypass or change that.

@hoonoh > what version of the letsencrypt container are you running ?

**Comment by hoonoh** [comment]
@buchdag tested with `jrcs/letsencrypt-nginx-proxy-companion:latest` with `jwilder/docker-gen:latest`

**Comment by Admin9705** [comment]
http://www.zdnet.com/article/lets-encrypt-disables-tls-sni-01-validation/ is this part of the problem?

**Comment by buchdag** [comment]
Nope, `simp_le` (the ACME client used in this project) does not use the `TLS-SNI-01` challenge.

**Comment by sabbane** [comment]
I also thought the issue is related to the tls-sni latest restriction. Is there a workaround for the issue till it's solved ?

**Comment by buchdag** [comment]
As no precise issue have been identified yet it will be pretty hard to solve it with a workaround.

Failed authorization are most often the result of a misconfiguration.

**Comment by sabbane** [comment]
The configuration isn't new and was working well. Just during the last automatic renewel the issue poped up. The only change I did now is update the container image from v1.5 to v1.7 .

**Comment by sabbane** [comment]
No, it failed with v1.5 and I thought it may be a problem with the tls-sni restrictions so I updated to the newest version v1.7 .

I get it to work now. I get it to work by disabling the firewall completely. Is there any specific ports needed by letsencrypt except the port 80 and 443 ?

**Comment by buchdag** [comment]
> Is there any specific ports needed by letsencrypt except the port 80 and 443 ?

For inbound ports that's all you need. The host on which I do most of the dev tests only has an SSH port + 80 and 443 opened. Do you think the doc is unclear or vague about the port 80 requirement ?

About `tls-sni-01`, let this be crystal clear for anybody reading this issue:

Neither this project nor `simp_le` (which it is based upon) use or even **can** use `tls-sni-01` challenge. Any issue with `tls-sni-01` challenge won't affect `letsencrypt-nginx-proxy-companion`.

On the other hand issues with `http-01` challenge most definitely will as it is the only supported challenge.

**Comment by sabbane** [comment]
So, that's weird for the port. on the server I have only these two ports and port 25 as standard ports. The other ports, such as ssh, are changed to another number.

So, thanks Buchdag for the support and also thanks for this great project !

**Comment by andre-dierker** [comment]
I had similar problems. After some attempts I found out that Letsencrypt's acme-server tries to reach the server via IPv6 if a AAAA record exist.
Docker starts by default without IPv6 support, so the server cannot be reached.
Possible solution: Start Docker with IPv6 support and add a CAA record or remove the AAAA record in the DNS.

**Comment by buchdag** [comment]
Regarding the CAA record, Let's Encrypt does not require it to be set but require the DNS provider of the domain to answer correctly to requests for a CAA record.

https://letsencrypt.org/docs/caa/

**Comment by jsaalfeld** [comment]
I'm having a similar issue. This is the relevant part from the docker-compose.yml from [my repo](https://github.com/OpenSlides/openslides-docker).
```
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - front
      - back
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/conf.d"
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - back
```
When I try to open the ```.well-known/acme-challenge/X``` from the browser i get redirected to the running application instead. This results in the error from letsencrypt. In the container itself the folder exists, but there is no ```X``` present and also while ```grep -ri .well-known *``` there is nothing found in the ```nginx-proxy``` container. I put a simple test.html-page in the ```/usr/share/nginx/html/.well-known/acme-challenge/``` but I can't access it via my url - I always get redirected to the running application.

**Comment by matt-hh** [comment]
Hi @jsaalfeld your letsencrypt container can't see the volumes from nginx container (/etc/nginx/vhost.d). Here is an example with the relevant parts:

```
  nginx_proxy:
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx_proxy

```
