### ISSUE TITLE
docker-compose file works for one host but fails for another

### ISSUE THREAD

**Issue by vmsh0** [JrCs/docker-letsencrypt-nginx-proxy-companion#336]
Hello,

I've been trying for the past two days to get `docker-letsencrypt-nginx-proxy-companion` to work for a website I'm setting up with docker-compose.

No matter what I do, one or more of the validations fail. I'm especially baffled (and also scared, at this point) because I'm using the exact same docker-compose file for another website successfully.

This is the docker-compose file I'm using. (failed authorizations URLs redacted)
```
version: "2"

# run before composing: docker network create nginx-proxy-net

services:
  proxy:
    restart: unless-stopped
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-net
  proxy-gen:
    restart: unless-stopped
    image: jwilder/docker-gen
    container_name: proxy-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - proxy
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]
  proxy-ssl-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-ssl-companion
    volumes_from:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=proxy-gen

  website-domain-namezzz-main-web:
    restart: unless-stopped
    image: nginx:1.13
    container_name: nginx-website-domain-namezzz-main
    volumes:
      - "./volumes/websites/website-domain-namezzz-main/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./volumes/websites/website-domain-namezzz-main/document_root/:/document_root/"
      - "./volumes/websites/website-domain-namezzz-main/nginx/logs/:/logs/"
    environment:
      - VIRTUAL_HOST=website-domain-namezzz.it,www.website-domain-namezzz.it,website-domain-namezzz.com,www.website-domain-namezzz.com
      - VIRTUAL_NETWORK=nginx-proxy-net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=website-domain-namezzz.it,www.website-domain-namezzz.it,website-domain-namezzz.com,www.website-domain-namezzz.com
      - LETSENCRYPT_EMAIL=email@address.ext
      - WEB_PHP_SOCKET=php:9000
    networks:
      - proxy-net
      - website-domain-namezzz-main-backend
  website-domain-namezzz-main-db:
    restart: unless-stopped
    image: mariadb:10.3
    container_name: mysql-website-domain-namezzz-main
    volumes:
      - "./volumes/websites/website-domain-namezzz-main/mysql/data/:/var/lib/mysql/"
      - "./volumes/websites/website-domain-namezzz-main/mysql/conf.d/:/etc/mysql/conf.d/"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Pxn1nX4ybTREHK8R
      - MYSQL_ROOT_PASSWORD=DgB6En3QF6ky4cfA
    networks:
      website-domain-namezzz-main-backend:
        aliases:
          - db
  website-domain-namezzz-main-phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin-website-domain-namezzz-main
    environment:
      - VIRTUAL_HOST=pma-gh30499.website-domain-namezzz.it
      - VIRTUAL_NETWORK=nginx-proxy-net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pma-gh30499.website-domain-namezzz.it
      - LETSENCRYPT_EMAIL=email@address.ext
      - PMA_HOST=db
      - PMA_ABSOLUTE_URL=https://pma-gh30499.website-domain-namezzz.it
    networks:
      - proxy-net
      - website-domain-namezzz-main-backend
  website-domain-namezzz-main-php:
    restart: unless-stopped
    build: ./images/php7.1-fpm-custom
    container_name: php-website-domain-namezzz-main
    volumes:
      - "./volumes/websites/website-domain-namezzz-main/document_root/:/document_root/"
    networks:
      website-domain-namezzz-main-backend:
        aliases:
          - php

networks:
  proxy-net:
    external:
      name: nginx-proxy-net
  website-domain-namezzz-main-backend:
    driver: bridge
```

These are the DNS zones for the two domains (I post only one as they are identical):
```
$TTL 3600
@	IN SOA [hidden]. [hidden]. (2018022002 86400 3600 3600000 300)
           IN NS      [hidden].
           IN NS      [hidden].
           IN A      [server dedicated IPv4]
           IN TXT    "1|www.website-domain-namezzz.it"
           IN CAA    0 issue "letsencrypt.org"
*          IN CNAME  website-domain-namezzz.it.
www        IN TXT    "l|it"
www        IN TXT    "3|welcome"
```

And finally, this is the log I get when running `docker-compose up`:
```
root@website-domain-namezzz:/srv/docker-website# docker-compose up
Starting php-website-domain-namezzz-main ...
Starting proxy ...
Starting nginx-website-domain-namezzz-main ...
Starting phpmyadmin-website-domain-namezzz-main ...
Starting proxy ... done
Starting proxy-gen ...
Recreating proxy-ssl-companion ... done
Attaching to php-website-domain-namezzz-main, nginx-website-domain-namezzz-main, phpmyadmin-website-domain-namezzz-main, mysql-website-domain-namezzz-main, proxy, proxy-gen, proxy-ssl-companion
php-website-domain-namezzz-main           | [21-Feb-2018 10:49:52] NOTICE: fpm is running, pid 1
php-website-domain-namezzz-main           | [21-Feb-2018 10:49:52] NOTICE: ready to handle connections
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:52 [warn] 1#1: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:34
proxy                                     | nginx: [warn] duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:34
proxy                                     | 2018/02/21 10:49:53 [warn] 1#1: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:34
proxy-gen                                 | 2018/02/21 10:49:53 Generated '/etc/nginx/conf.d/default.conf' from 5 containers
proxy-gen                                 | 2018/02/21 10:49:53 Sending container 'proxy' signal '1'
proxy-gen                                 | 2018/02/21 10:49:53 Watching docker events
proxy-gen                                 | 2018/02/21 10:49:53 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
proxy-gen                                 | 2018/02/21 10:49:53 Received event start for container 89ec2ea15bf2
proxy-ssl-companion                       | Sleep for 3600s
proxy-ssl-companion                       | 2018/02/21 10:49:54 Generated '/app/letsencrypt_service_data' from 7 containers
proxy-ssl-companion                       | 2018/02/21 10:49:54 Running '/app/update_certs'
proxy-ssl-companion                       | 2018/02/21 10:49:54 Watching docker events
proxy-ssl-companion                       | 2018/02/21 10:49:54 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
proxy-ssl-companion                       | /etc/nginx/certs/website-domain-namezzz.it /app
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,139 CRIT Supervisor running as root (no user in config file)
proxy-ssl-companion                       | Reloading nginx docker-gen (using separate container proxy-gen)...
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,147 WARN Included extra file "/etc/supervisor.d/nginx.ini" during parsing
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,147 WARN Included extra file "/etc/supervisor.d/php.ini" during parsing
proxy-ssl-companion                       | Creating/renewal website-domain-namezzz.it certificates... (website-domain-namezzz.it www.website-domain-namezzz.it website-domain-namezzz.com www.website-domain-namezzz.com)
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,180 INFO RPC interface 'supervisor' initialized
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,184 CRIT Server 'unix_http_server' running without any HTTP authentication checking
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:54,184 INFO supervisord started with pid 1
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] mysqld (mysqld 10.3.4-MariaDB-10.3.4+maria~jessie) starting as process 1 ...
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Uses event mutexes
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Using Linux native AIO
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Number of pools: 1
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Waiting for purge to start
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: 5.7.20 started; log sequence number 1632342
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] Server socket created on IP: '::'.
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] InnoDB: Buffer pool(s) load completed at 180221 10:49:54
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] Reading of all Master_info entries succeded
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] Added new Master_info '' to hash table
mysql-website-domain-namezzz-main         | 2018-02-21 10:49:54 0 [Note] mysqld: ready for connections.
mysql-website-domain-namezzz-main         | Version: '10.3.4-MariaDB-10.3.4+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
proxy-ssl-companion                       | 2018-02-21 10:49:54,738:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:55,187 INFO spawned: 'php-fpm' with pid 13
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:55,197 INFO spawned: 'nginx' with pid 14
proxy-ssl-companion                       | 2018-02-21 10:49:55,523:INFO:simp_le:1356: Generating new account key
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:56,306 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpmyadmin-website-domain-namezzz-main    | 2018-02-21 10:49:56,306 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxy-gen                                 | 2018/02/21 10:49:58 Debounce minTimer fired
proxy-gen                                 | 2018/02/21 10:49:58 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
proxy                                     | website-domain-namezzz.com 66.133.109.36 - - [21/Feb/2018:10:50:00 +0000] "GET /.well-known/acme-challenge/EMRatyIB4DPQ7Utg_URifHlU3RNXvmoWRy_0wHDUfto HTTP/1.1" 500 193 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
proxy                                     | website-domain-namezzz.it 66.133.109.36 - - [21/Feb/2018:10:50:00 +0000] "GET /.well-known/acme-challenge/ece4enjQRkcp849TEv2xckQTUjm-3jPHgx3eQwoXKmA HTTP/1.1" 500 193 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
proxy-ssl-companion                       | 2018-02-21 10:50:00,586:INFO:simp_le:1455: Generating new certificate private key
proxy-ssl-companion                       | 2018-02-21 10:50:02,440:ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: [redacted]
proxy-ssl-companion                       | 2018-02-21 10:50:02,445:INFO:simp_le:463: Saving account_key.json
proxy-ssl-companion                       | Challenge validation has failed, see error log.
proxy-ssl-companion                       |
proxy-ssl-companion                       | Debugging tips: -v improves output verbosity. Help is available under --help.
proxy-ssl-companion                       | /app
proxy-ssl-companion                       | /etc/nginx/certs/pma-gh30499.website-domain-namezzz.it /app
proxy-ssl-companion                       | Creating/renewal pma-gh30499.website-domain-namezzz.it certificates... (pma-gh30499.website-domain-namezzz.it)
proxy-ssl-companion                       | 2018-02-21 10:50:02,896:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
proxy-ssl-companion                       | 2018-02-21 10:50:11,498:INFO:simp_le:1455: Generating new certificate private key
proxy                                     | pma-gh30499.website-domain-namezzz.it 66.133.109.36 - - [21/Feb/2018:10:50:11 +0000] "GET /.well-known/acme-challenge/Lsr4snhGhQXUKZiJVH31WMZUDCh9PgcJDcy5AQvFoY0 HTTP/1.1" 403 162 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
proxy-ssl-companion                       | 2018-02-21 10:50:13,250:ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: [redacted]
proxy-ssl-companion                       | Challenge validation has failed, see error log.
proxy-ssl-companion                       |
proxy-ssl-companion                       | Debugging tips: -v improves output verbosity. Help is available under --help.
proxy-ssl-companion                       | /app
proxy-ssl-companion                       | Sleep for 3600s
```

Note: I'm using a slightly modified `nginx-compose-v2.tmpl` for `docker-gen`, but I don't think that matters. I just changed how the container internal IPs are obtained, as the original version didn't work for me. The reverse proxy works fine, I can load both containers. If you need, I can post the template as well.
