### ISSUE TITLE
Error: nginx-proxy container nginx isn't running.

### ISSUE THREAD

**Issue by gcleaves** [JrCs/docker-letsencrypt-nginx-proxy-companion#355]
I see the following error when I do `docker logs -f nginx-letsencrypt`
> Error: nginx-proxy container nginx isn't running.

Is this expected behaviour? Nothing seems to get created in the certs folder except `dhparam.pem`. I would expect to see certificates for the last container I start with the `"VIRTUAL_HOST=domain.com"` variable. Any suggestions? 

I also find it strange that the letsencrypt logs says
>Generated '/app/letsencrypt_service_data' from 11 containers

Yes, I have a lot of containers running, but only 1 of them has the `"VIRTUAL_HOST=domain.com"` variable. Are wires getting crossed?

Any help would be appreciated!

**Comment by buchdag** [comment]
`VIRTUAL_HOST` control proxying by nginx-proxy, not certificate creation by this container.

You should probably start by reading the doc.

**Comment by gcleaves** [comment]
OK duchbag, I'll try reading the docs again!

**Comment by buchdag** [comment]
> OK duchbag

buchdag 😄

**Comment by sereysethy** [comment]
Hi I am sorry but my system worked fine for months until recently I have the same problem. I think it is because of the new update. @gcleaves @buchdag  can you tell me where to look at? I assure you I have read the doc :-) I set up my system since last year.

**Comment by buchdag** [comment]
Can you try with tagged version `v1.7` ?

**Comment by sereysethy** [comment]
@buchdag Thanks. It solves the problem. Can you let me know what to change exactly if I upgrade to use the latest version? Currently everything is running in the same service stack, nginx-proxy, docker-gen, letsencrypt...

**Comment by buchdag** [comment]
@sereysethy We'll try to see why the LE companion has issue with your nginx container. Can you give us more info about your configuration (compose file or CLI commands you run your containers with for instance) ?

**Comment by buchdag** [comment]
@sereysethy could you try again with tagged version `dev` ?

**Comment by sereysethy** [comment]
@buchdag I tried with `dev` tag here is the error message

```
/app/entrypoint.sh: line 57: ACME_CA_URI: unbound variable
```

I think I need to provide the value to `ACME_CA_URI`. Does it have a default value?

**Comment by buchdag** [comment]
Nope, I made mistake, I'm correcting it and pushing a fixed `dev` version.

**Comment by sereysethy** [comment]
@buchdag I run it as a service in a docker swarm environment, only nginx has several instances (but I dont think that is the issue). here is the complete config:

```
version: '3'

services:
  nginx-proxy:
    image: nginxproxy_nginx-proxy
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /opt/nginx-proxy/data/certs/:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    volumes:
      - /opt/nginx-proxy/data/certs/:/etc/nginx/certs:rw
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
networks:
  frontend:
```

I think `label` is not yet supported ... this configuration were changed slightly when I updated to the newer version of letsencrypt, especially the new environment variables

```
NGINX_PROXY_CONTAINER: nginx-proxy
NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
```

Before the config file is much simpler. Now I have no idea what to add/remove.
