### ISSUE TITLE
Can't change the external_url to https in Gitlab in combination with docker-letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by moezChr** [JrCs/docker-letsencrypt-nginx-proxy-companion#357]
Hello,
I am currently running into an issue with the combination of the docker-letsencrypt-nginx-proxy-companion and Gitlab. 
Gitlab is running and everything is working properly, but if I set the `external_url` in the `gitlab.rb` file to `https://gitlab.domain.com` instead of `http://gitlab.domain.com` it is not working anymore and I get `502 ERROR Bad Gateway` as response. I want to set the `external_url` to change the URL to clone a repository from http to https.

nginx => error.log:
`2018/04/03 18:10:49 [error] 75#75: *8 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: gitlab.domain.com, request: "GET / HTTP/2.0", upstream: "http://x.x.x.x:80/", host: "gitlab.domain.com"`

`2018/04/03 18:10:49 [error] 75#75: *8 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: gitlab.domain.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://x.x.x.x::80/favicon.ico", host:`

docker-letsencrypt-nginx-proxy-companion => docker-compose.yml

```
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - ./nginx/logs/:/var/log/nginx/
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
networks:
  default:
    external:
      name: nginx-proxy
```

Gitlab-CE => docker-compose.yml
```
version:  "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
        VIRTUAL_HOST: gitlab.domain.com
        LETSENCRYPT_HOST: gitlab.domain.com
        LETSENCRYPT_EMAIL: support@domain.com
        hostname: gitlab.domain.com
        GITLAB_OMNIBUS_CONFIG: |
          external_url = 'https://gitlab.domain.com'
          gitlab_rails['gitlab_shell_ssh_port'] = 22
    expose:
      - 80
      - 443
      - 22
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
networks:
  default:
    external:
      name: nginx-proxy
```

Could you help me with the issue? 

Sincerely,
moeChr
