### ISSUE TITLE
[Question] Redirected too many times

### ISSUE THREAD

**Issue by Matts** [JrCs/docker-letsencrypt-nginx-proxy-companion#363]
Hi, I am not finding any consistent source on how to solve an http/https redirection loop. Everything is setup to documentation, and it has also worked like a month ago. But now the config below just gives a redirect loop.

Note: This is with using the jwilders nginx proxy

```
nginx:
        image: nginx:1.0
        ports:
        - "90:80"
        networks:
            net:
                aliases:
                - ezcb.local
        depends_on:
        - mysql
        - php
        environment:
           VIRTUAL_HOST: redacted
           VIRTUAL_PORT: '80'
           HTTPS_METHOD: redirect
           HSTS: 'off'
           LETSENCRYPT_EMAIL: redacted
           LETSENCRYPT_HOST: redacted

```

Thanks in advance
