### ISSUE TITLE
label stable or latest don have the cert_status script

### ISSUE THREAD

**Issue by rene-gomez** [JrCs/docker-letsencrypt-nginx-proxy-companion#371]
docker exec nginx-letsencrypt /app/cert_status

rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/app/cert_status\": stat /app/cert_status: no such file or directory"

DockerFile:
```

version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/www/vhost.d:/etc/nginx/vhost.d
      - /var/www/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    labels:
      - com.example.nginx_proxy=true


  dockergen:
    image: jwilder/docker-gen
    restart: always
    container_name: nginx-gen
    command: -notify "docker-label-sighup com.example.nginx_proxy" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#    command: -watch -only-exposed /etc/docker-gen/templates/debug.tmpl /etc/docker-gen/log/debug.log
#    command: -notify "docker-label-sighup com.example.nginx_proxy" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./templates:/etc/docker-gen/templates:ro
      - nginx-proxy:/etc/nginx/conf.d
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
#      - ./volumes/proxy/templates:/etc/docker-gen/templates:ro
    volumes_from:
      - nginx-proxy


  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    container_name: nginx-letsencrypt
    volumes:
      - /var/www/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./app:/app
    volumes_from:
      - nginx-proxy
volumes:
  nginx-proxy:


networks:
  default:
    external:
      name: nginx-proxy

```

**Comment by buchdag** [comment]
Hi.

`stable` is currently `v1.7`, the /app/cert_status script was added in `v1.8`.

/app/cert_status works fine with `latest`, just tested it.

**Comment by rene-gomez** [comment]
Hi @buchdag this is my compose file
```

 proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    container_name: nginx-letsencrypt
    volumes:
      - /var/www/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
```

And this is the result

`docker exec nginx-letsencrypt /app/cert_status`

> 
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/app/cert_status\": stat /app/cert_status: no such file or directory"
