### ISSUE TITLE
Image latest /app/force_renew does not work Error: nginx-proxy container isn't running.

### ISSUE THREAD

**Issue by rene-gomez** [JrCs/docker-letsencrypt-nginx-proxy-companion#375]
This is my docker-compose.yml 

```
  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    container_name: nginx-letsencrypt
    volumes:
      - /var/www/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

```

The issue appear when try this command: docker exec nginx-letsencrypt /app/force_renew

The console respond:

Error: nginx-proxy container   isn't running.

The result of the docker ps : 
`
jrcs/letsencrypt-nginx-proxy-companion:latest   "/bin/bash /app/en..."   9 minutes ago       Up 9 minutes                                                   nginx-letsencrypt
`
