### ISSUE TITLE
Error during certificate generation

### ISSUE THREAD

**Issue by techhazard** [JrCs/docker-letsencrypt-nginx-proxy-companion#397]
I'm using the multiple container setup and I get an error during certificate creation

This is what I get
```
Attaching to docker_whoami_1, docker_nginx_1, docker_docker-gen_1, docker_nginx-letsencrypt_1
whoami_1             | Listening on :8000
docker-gen_1         | 2018/06/06 17:31:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
docker-gen_1         | 2018/06/06 17:31:12 Watching docker events
docker-gen_1         | 2018/06/06 17:31:13 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
docker-gen_1         | 2018/06/06 17:31:13 Received event start for container 6abae88030a5
nginx-letsencrypt_1  | /etc/nginx/certs/_test_whoami.mydomainname.com /app
nginx-letsencrypt_1  | Reloading nginx docker-gen (using separate container 9e306e12f49806f1a31528dce265dba658e09c2702e9aa36f780990bd7af28d2)...
nginx-letsencrypt_1  | 2018/06/06 17:31:13 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx-letsencrypt_1  | 2018/06/06 17:31:13 Watching docker events
docker-gen_1         | 2018/06/06 17:31:13 Received signal: hangup
docker-gen_1         | 2018/06/06 17:31:13 Received signal: hangup
nginx-letsencrypt_1  | Reloading nginx (using separate container f0b0ec9d364dac63dc833d7a6003c36c85286672792a0eaaa969e3542a3831a4)...
nginx-letsencrypt_1  | Creating/renewal whoami.mydomainname.com certificates... (whoami.mydomainname.com)
nginx-letsencrypt_1  | 2018/06/06 17:31:13 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
docker-gen_1         | 2018/06/06 17:31:13 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt_1  | 2018-06-06 17:31:13,564:INFO:simp_le:1382: Generating new account key
nginx-letsencrypt_1  | 2018-06-06 17:31:14,708:WARNING:simp_le:1397: --email was not provided; ACME CA will have no way of contacting you.
nginx-letsencrypt_1  | 2018-06-06 17:31:15,147:INFO:simp_le:1407: By using simp_le, you implicitly agree to the CA's terms of service: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
nginx-letsencrypt_1  | 2018-06-06 17:31:15,895:INFO:simp_le:1479: Generating new certificate private key
docker-gen_1         | 2018/06/06 17:31:18 Debounce minTimer fired
docker-gen_1         | 2018/06/06 17:31:18 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_1              | whoami.mydomainname.com 52.29.173.72 - - [06/Jun/2018:17:31:30 +0000] "GET /.well-known/acme-challenge/2qiA-CjiliUGj7JFU6qMWdM5f96JF9DcOXWfjnuN4F4 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx_1              | whoami.mydomainname.com 13.58.30.69 - - [06/Jun/2018:17:31:30 +0000] "GET /.well-known/acme-challenge/2qiA-CjiliUGj7JFU6qMWdM5f96JF9DcOXWfjnuN4F4 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx_1              | whoami.mydomainname.com 34.213.106.112 - - [06/Jun/2018:17:31:30 +0000] "GET /.well-known/acme-challenge/2qiA-CjiliUGj7JFU6qMWdM5f96JF9DcOXWfjnuN4F4 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-letsencrypt_1  | Traceback (most recent call last):
nginx-letsencrypt_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
nginx-letsencrypt_1  |     return main_with_exceptions(cli_args)
nginx-letsencrypt_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
nginx-letsencrypt_1  |     persist_new_data(args, existing_data)
nginx-letsencrypt_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1483, in persist_new_data
nginx-letsencrypt_1  |     certr = get_certr(client, csr, authorizations)
nginx-letsencrypt_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1425, in get_certr
nginx-letsencrypt_1  |     ', '.join(authzr.uri for _, authzr in error.exhausted)
nginx-letsencrypt_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1425, in <genexpr>
nginx-letsencrypt_1  |     ', '.join(authzr.uri for _, authzr in error.exhausted)
nginx-letsencrypt_1  | ValueError: too many values to unpack
nginx-letsencrypt_1  |
nginx-letsencrypt_1  | Unhandled error has happened, traceback is above
nginx-letsencrypt_1  |
nginx-letsencrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt_1  | /app
nginx-letsencrypt_1  | Sleep for 3600s
Gracefully stopping... (press Ctrl+C again to force)
```

Here is the `docker-compose.yml` I'm using:
```yml
version: '3.6'

services:

  # docker run -d -p 80:80 -p 443:443 \
  # --name nginx \
  # -v /etc/nginx/conf.d  \
  # -v /etc/nginx/vhost.d \
  # -v /usr/share/nginx/html \
  # -v /path/to/certs:/etc/nginx/certs:ro \
  # --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  # nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_vhost:/etc/nginx/vhost.d:ro
      - nginx_html:/usr/share/nginx/html:ro
      - certificates:/etc/nginx/certs:ro
    networks:
      - nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  # docker run -d \
  # --name nginx-gen \
  # --volumes-from nginx \
  # -v /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
  # -v /var/run/docker.sock:/tmp/docker.sock:ro \
  # --label com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen \
  # jwilder/docker-gen \
  # -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  docker-gen:
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - nginx_conf:/etc/nginx/conf.d:rw
      - certificates:/etc/nginx/certs:ro
    command: [
      "-notify-sighup",
      "docker_nginx_1",
      "-watch",
      "-wait",
      "5s:30s",
      "/etc/docker-gen/templates/nginx.tmpl",
      "/etc/nginx/conf.d/default.conf"
    ]
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    depends_on:
      - nginx


  # docker run -d \
  # --name nginx-letsencrypt \
  # --volumes-from nginx \
  # -v /path/to/certs:/etc/nginx/certs:rw \
  # -v /var/run/docker.sock:/var/run/docker.sock:ro \
  # jrcs/letsencrypt-nginx-proxy-companion

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx_conf:/etc/nginx/conf.d:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - nginx_html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certificates:/etc/nginx/certs:rw
    depends_on:
      - nginx
      - docker-gen


  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.mydomainname.com
      - LETSENCRYPT_HOST=whoami.mydomainname.com
      - LETSENCRYPT_TEST=true


networks:
  nginx:

volumes:
  nginx_html:
  nginx_vhost:
  nginx_conf:
  certificates:
```

I got the feeling that I'm missing something tiny.
What am I doing wrong?

**Comment by techhazard** [comment]
I've been able to do a workaround by using the combined nginx+docker-gen image of jwilder/nginx-proxy like so:
```yml
version: '3.6'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - nginx_html:/usr/share/nginx/html:ro
      - certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx_conf:/etc/nginx/conf.d:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - nginx_html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certificates:/etc/nginx/certs:rw
    depends_on:
      - nginx-proxy


  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.mydomainname.com
      - LETSENCRYPT_HOST=whoami.mydomainname.com
      - LETSENCRYPT_TEST=true
    networks:
      - nginx


networks:
  nginx:

volumes:
  nginx_html:
  nginx_vhost:
  nginx_conf:
  certificates:

```
