### ISSUE TITLE
Challenge Failed: Connection Error (DDNS)

### ISSUE THREAD

**Issue by jordangarside** [JrCs/docker-letsencrypt-nginx-proxy-companion#417]
Hi,

I spent quite a bit of time trying to figure out what's causing this and am at a loss.

I have DDNS setup through namecheap -> tomato router -> computer.
I'm using their "A+ Dynamic DNS Record" and I also tried just a standard A Record.
Port 443 is definitely publicly accessible (not blocked by ISP or anything).

It feels like the challenge is just not getting hosted locally.

Thanks for any help!

Netstat:
```sh
tcp6       0      0 :::80                   :::*                    LISTEN      19048/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      19036/docker-proxy
```

Log:
```json
{
  "identifier": {
    "type": "dns",
    "value": "www.atomsandbits.ai"
  },
  "status": "invalid",
  "expires": "2018-07-24T00:08:56Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Fetching http://www.atomsandbits.ai/.well-known/acme-challenge/xOM-bYeaH_-0ZX_tDWDHF_NMPdzsyl6gCuvul3vJ7jc: Timeout during connect (likely firewall problem)",
        "status": 400
      },
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/6kI5qbmFJqdeCVkA8W26Neh1X2ncnjBOIfD-MmesMuY/149390393",
      "token": "xOM-bYeaH_-0ZX_tDWDHF_NMPdzsyl6gCuvul3vJ7jc",
      "keyAuthorization": "xOM-bYeaH_-0ZX_tDWDHF_NMPdzsyl6gCuvul3vJ7jc.58HYOuxGNkmgxJNP-C-RKLDZUermSL9dKX5HFFkWb74",
      "validationRecord": [
        {
          "url": "http://www.atomsandbits.ai/.well-known/acme-challenge/xOM-bYeaH_-0ZX_tDWDHF_NMPdzsyl6gCuvul3vJ7jc",
          "hostname": "www.atomsandbits.ai",
          "port": "80",
          "addressesResolved": [
            "142.151.170.244"
          ],
          "addressUsed": "142.151.170.244"
        }
      ]
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/6kI5qbmFJqdeCVkA8W26Neh1X2ncnjBOIfD-MmesMuY/149390394",
      "token": "vpHMHB6N3ltH7oxdO3aMNRHnnEsiFIeKHiI2XVF1XFw"
    },
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/6kI5qbmFJqdeCVkA8W26Neh1X2ncnjBOIfD-MmesMuY/149390395",
      "token": "G1gf7xOz8QBi6aOUxFi_Trgvr3npx-DPuY3XnNz7Mic"
    }
  ],
  "combinations": [
    [
      2
    ],
    [
      1
    ],
    [
      0
    ]
  ]
}

```

**Comment by jeffusan** [comment]
I'm having the same issue, and the log from letsencrypt is identical. The connection is always refused with a 400 error.

Here's an example of my docker-compose:

```
version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /opt/srv/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /opt/srv/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy

  api:
    image: image1
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=api.domain.com
      - LETSENCRYPT_HOST=api.domain.com
      - LETSENCRYPT_EMAIL=google@gmail.com

  static:
    image: image2
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=static.domain.com,dev.domain.com
      - LETSENCRYPT_HOST=static.domain.com,dev.domain.com
      - LETSENCRYPT_EMAIL=google@gmail.com
```

I deployed this successfully a little over a month ago.
