### ISSUE TITLE
Ship example.com and foo.example.com - SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by oliverlorenz** [JrCs/docker-letsencrypt-nginx-proxy-companion#419]
Hi!

**Context**

I try to run two `nginx` docker container behind `nginx-proxy`. One is shipping `example.com` another one ships `foo.example.com`. I use this project to run with https.

**The problem**

I open `https://example.com` in the browser and all seems fine. I open `https://foo.example.com` in the browser an get a error with the following message:

```
foo.example.com uses an invalid security certificate. 
The certificate is only valid for example.com. 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
This is my docker compose file:
```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

################################################################################
# websites
################################################################################

  example.com:
    image: nginx:latest
    container_name: example.com
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST:example.com
      LETSENCRYPT_EMAIL: mail@example.com
    depends_on:
      - letsencrypt
      - nginx-proxy

  foo.example.com:
    image: nginx:latest
    container_name: foo.example.com
    environment:
      VIRTUAL_HOST: foo.example.com
      LETSENCRYPT_HOST: foo.example.com
      LETSENCRYPT_EMAIL: mail@example.com
    depends_on:
      - letsencrypt
      - nginx-proxy

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
```

Has somebody a idea what I can do to ship both sites with working https?
Thank you :slightly_smiling_face:
