### ISSUE TITLE
nginx config doesn't follow my VIRTUAL_PORT

### ISSUE THREAD

**Issue by Yogarine** [JrCs/docker-letsencrypt-nginx-proxy-companion#421]
I've used nginx-proxy with containers running on several ports without any issues using VIRTUAL_PORT to map it to the correct port.

Now I've started using `docker-letsencrypt-nginx-proxy-companion` but since I've added this container it seems nginx-proxy is ignoreing my VIRTUAL_PORT.

Here is my docker-compose.yml for the nginx-proxy:
```
version: "3"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx-certs:/etc/nginx/certs:ro"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "./etc/nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx-certs:/etc/nginx/certs:rw"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
```

And here is the docker-compose.yml snippet for my container that I'm trying to run:
```
  something:
    environment:
      - VIRTUAL_HOST=something.somedomain.nl
      - VIRTUAL_PORT=3081
      - LETSENCRYPT_HOST=something.somedomain.nl
      - LETSENCRYPT_EMAIL=ops@foo.nl
      - PORT=3081
    image: 'somebody/something:latest'
```

Yet the upstream in /etc/nginx/conf.d/default.conf points to port 80:
```
# something.somedomain.nl
upstream something.somedomain.nl {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				## Can be connected with "someproject_default" network
			# someproject_something_1
			server 172.27.0.20:80;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
}
```

I'm not sure why it complains about the other containers not being connectible. I've made sure all containers are in the same network.
