### ISSUE TITLE
Unable to generate any certificate

### ISSUE THREAD

**Issue by schiz0phr3ne** [JrCs/docker-letsencrypt-nginx-proxy-companion#426]
Hello !

It's been a few days now that I'm looking for how to generate a certificate for a subdomain on my NAS.

I use the nginx-proxy container from jwilder, with the JrCs companion container.
My tests are done on the Portainer container, but I made others with the container NextCloud from linuxserver.
All containers are up to date, via watchtower.

The parameters of the different containers (filled in via the OpenMediaVault graphical interface and its docker plugin ; only pertinent informations, for this case, are here):

**nginx-proxy :**
- 80:80 tcp et 443:443 tcp
- /var/run/docker.sock:/tmp/docker.sock:ro
- /docker/certs:/etc/nginx/certs
- /docker/nginx_proxy/dhparam:/etc/nginx/dhparam
- --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

**companion :**
- /docker/nginx_proxy/etc/nginx/vhost.d:/etc/nginx/vhost.d
- /docker/nginx_proxy/usr/share/nginx/html:/usr/share/nginx/html
- /var/run/docker.sock:/var/run/docker.sock:ro
- /docker/certs:/etc/nginx/certs
- volume from nginx-proxy

**Portainer :**
- 59000:9000 tcp
- VIRTUAL_HOST = sub.domain.com
- LETSENCRYPT_HOST = sub.domain.com
- LETSENCRYPT_EMAIL = mail@mail.com

Note that joining Portainer via the sub.domain.com address works. Ports 80 and 443 are open in my router.

Only, when the companion tries to generate a certificate, I have the following error in the container log
 : `CA marked some of the authorizations as invalid, which likely means it could not access [...]`

I did other tests, by informing VIRTUAL_PORT, VIRTUAL_PROTO, etc. but I still have the same result (I also had an automatic redirection of the HTTP to the HTTPS, without really understanding why).

Is there a problem in my way of doing things?
If more information is needed, I can try to provide you with it.

Regards,

schizophrene

**Comment by simbelcode** [comment]
I have the exact same problem.
I use the setup in separate containers using dockergen and nginx:stable to proxy a few apache containers. This has worked for me so far and I already retrieved several certificates.
It's only for a few days now, that I get the same error @schizophrene has, whenever I try to add a new virtual host.

This is my compose file:
````
version: '2'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /srv/docker-staging/certs:/etc/nginx/certs:ro
      - /srv/docker-staging/htpasswd:/etc/nginx/htpasswd

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    depends_on:
      - nginx

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx
    volumes:
      - /srv/docker-staging/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
    depends_on:
      - docker-gen

networks:
  default:
    external:
      name: proxy
````

The containers are started this way:
````
httpd:
        image: httpd:${CONTAINER_HTTPD_VERSION}
        expose:
            - "80"
        volumes:
            - "${PROJECT_ROOT}:/var/www:cached"
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${VIRTUAL_HOST}
        networks:
            - proxy
            - default
````
Any idea whats causing the problem?
