### ISSUE TITLE
Nginx proxy not loading the correct certificates until manual reload + excluding host from https

### ISSUE THREAD

**Issue by P4sca1** [JrCs/docker-letsencrypt-nginx-proxy-companion#433]
I'm using this docker image along with a seperate nginx and docker-gen container.
Everything works fine most of the time, however sometimes the nginx proxy uses the default certificate instead of the generated ones, even if the nginx configuration is correct. Manually reloading the nginx container using `docker container exec container_id nginx -s reload` solves the problem.

Here are the relevant parts of my docker-compose file (using Docker Swarm):
```
version: "3"

services:
nginx-proxy:
    image: nginx:mainline-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ips/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /home/ips/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /home/ips/nginx-proxy/html:/usr/share/nginx/html
      - /home/ips/nginx-proxy/certs:/etc/nginx/certs:ro
      - /home/ips/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: ""
    volumes:
      - /home/ips/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /home/ips/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /home/ips/nginx-proxy/html:/usr/share/nginx/html
      - /home/ips/nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/ips/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - proxy
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - /home/ips/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /home/ips/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /home/ips/nginx-proxy/html:/usr/share/nginx/html
      - /home/ips/nginx-proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
egm-web:
    image: nginx:mainline-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    environment:
      VIRTUAL_HOST: mydomain.de,www.mydomain.de,myotherdomain.com,de.myotherdomain.com,en.myotherdomain.com,loading.mydomain.de
      LETSENCRYPT_HOST: mydomain.de,www.mydomain.de,myotherdomain.com,de.myotherdomain.com,en.myotherdomain.com
      LETSENCRYPT_EMAIL: admin@mydomain.de
    volumes:
      - /home/ips/egm-web/files:/files
      - /home/ips/egm-web/conf.d:/etc/nginx/conf.d
      - /home/ips/egm-web/snippets:/etc/nginx/snippets
      - /home/ips/egm-web/nginx.conf:/etc/nginx/nginx.conf
      - /home/ips/egm-web/fastcgi_params:/etc/nginx/fastcgi_params
    networks:
      - proxy
      - egm-web
```
Also, is it possible to exclude a host in `VIRTUAL_HOST`, that is not listed in `LETSENCRYPT_HOST` (`loading.mydomain.de` in this case) from https? I would like to have this virtual host only served via http.
