### ISSUE TITLE
Wrong common name for multiple hostnames

### ISSUE THREAD

**Issue by Reldeis** [JrCs/docker-letsencrypt-nginx-proxy-companion#44]
Hi,

I want to issue an certificate for my domainroot www.willtho.com which should also be valid for willtho.com and mail.willtho.com. A valid certificate gets created, but its CN is mail.[...] instead of www.[...]. Is there a way to force www.willtho.com as the CN?

My docker-compose.yml

```
[...] 
 nginx_gen:
    image: jwilder/docker-gen
    container_name: nginx_gen
    restart: always
    volumes_from:
    - nginx_proxy
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /opt/proxy_tmpl/:/etc/docker-gen/templates:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/temp
lates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    restart: always
    volumes_from:
    - nginx_proxy
    depends_on:
    - nginx_gen
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/certs:/etc/nginx/certs:rw
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx_gen


 willtho:
    image: nginx
    container_name: willtho
    restart: always
    network_mode: bridge
    depends_on:
    - nginx_proxy
    - nginx_gen
    - nginx_letsencrypt
    ports:
    - "10800:80"
    - "10801:443"
    volumes:
    - /var/www/willtho.com/:/usr/share/nginx/html:ro
    environment:
    - VIRTUAL_HOST=www.willtho.com,mail.willtho.com,mail.willtho.com
    - LETSENCRYPT_HOST=www.willtho.com,willtho.com,mail.willtho.com
    - LETSENCRYPT_EMAIL=xxx@willtho.com
[...]
 ```
every cert is linked to www.willtho.com:
```
/etc/certs # ll
total 24
drwxr-xr-x   5 root root 4096 Mar 29 17:38 ./
drwxr-xr-x 101 root root 4096 Mar 29 11:03 ../
-rw-r--r--   1 root root  424 Mar 29 17:05 dhparam.pem
lrwxrwxrwx   1 root root   31 Mar 29 17:38 mail.willtho.com.crt -> ./www.willtho.com/fullchain.pem
lrwxrwxrwx   1 root root   13 Mar 29 17:38 mail.willtho.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx   1 root root   25 Mar 29 17:38 mail.willtho.com.key -> ./www.willtho.com/key.pem
[...]
lrwxrwxrwx   1 root root   31 Mar 29 17:38 willtho.com.crt -> ./www.willtho.com/fullchain.pem
lrwxrwxrwx   1 root root   13 Mar 29 17:38 willtho.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx   1 root root   25 Mar 29 17:38 willtho.com.key -> ./www.willtho.com/key.pem
drwxr-xr-x   2 root root 4096 Mar 29 17:38 www.willtho.com/
lrwxrwxrwx   1 root root   31 Mar 29 17:38 www.willtho.com.crt -> ./www.willtho.com/fullchain.pem
lrwxrwxrwx   1 root root   13 Mar 29 17:38 www.willtho.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx   1 root root   25 Mar 29 17:38 www.willtho.com.key -> ./www.willtho.com/key.pem
[...]
```
and last but not least, a sample output from ssllabs.com
```


Server Key and Certificate #1
Subject 	mail.willtho.com
Fingerprint SHA1: b7b1a29b3fdaf076e28688f71537cf880148eee2
Pin SHA256: CimFnieqN4F54Hu74MO/cKeZKv6fDRd/scS2aBiTfyw=
Common names 	mail.willtho.com
Alternative names 	mail.willtho.com willtho.com www.willtho.com
Valid from 	Tue, 29 Mar 2016 14:15:00 UTC
Valid until 	Mon, 27 Jun 2016 14:15:00 UTC (expires in 2 months and 28 days)
Key 	RSA 4096 bits (e 65537)
Weak key (Debian) 	No
Issuer 	Let's Encrypt Authority X3
AIA: http://cert.int-x3.letsencrypt.org/
Signature algorithm 	SHA256withRSA
Extended Validation 	No
Certificate Transparency 	No
Revocation information 	OCSP
OCSP: http://ocsp.int-x3.letsencrypt.org/
Revocation status 	Good (not revoked)
Trusted 	Yes
```
