### ISSUE TITLE
Standalone Certificates  (beta) issue

### ISSUE THREAD

**Issue by bigbennyb** [JrCs/docker-letsencrypt-nginx-proxy-companion#440]
Hi,

I'm trying to use the [Standalone certificates beta](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)).

I have a set up with three containers.

My docker-compose

```
version: '3'

services:
  nginx-proxy:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:dev
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./app/docker-gen.cfg:/app/letsencrypt_user_data:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx-proxy"


networks:
  default:
    external:
      name: mynetwork
```

Then my wordpress websites:
```
version: '3.1'

services:

  site:
    image: wordpress
    environment:
      - VIRTUAL_HOST=yourdomain.tld,www.yourdomain.tld,othersite.tld,www.othersite.tld
      - LETSENCRYPT_STANDALONE_CERTS=('web' 'othersite')
      - LETSENCRYPT_web_HOST=('yourdomain.tld' 'www.yourdomain.tld')
      - LETSENCRYPT_othersite_HOST=('othersite.tld' 'www.othersite.tld')

 networks:
  default:
    external:
      name: mynetwork
```

Content of the ./app/docker-gen.cfg file, i'm using the basic example provided

```
[[config]]
template = "/etc/nginx/nginx.conf.tmpl"
dest = "/etc/nginx/sites-available/default"
onlyexposed = true
notifycmd = "/etc/init.d/nginx reload"

[[config]]
template = "/etc/logrotate.conf.tmpl"
dest = "/etc/logrotate.d/docker"
watch = true

[[config]]
template = "/etc/docker-gen/templates/nginx.tmpl"
dest = "/etc/nginx/conf.d/default.conf"
watch = true
wait = "500ms:2s"

[config.NotifyContainers]
nginx = 1  # 1 is a signal number to be sent; here SIGHUP
e75a60548dc9 = 1  # a key can be either container name (nginx) or ID
```

The result is one SSL cert is generated for yourdomain.tld  with alternate name www.yourdomain.tld.

But no SSL cert for othersite.tld www.othersite.tld

I don't understand well the following part of the doc:

> The user configuration file is a collection of bash variables and array, and follows the syntax of the /app/letsencrypt_service_data file that get created by docker-gen.

That's why i used the basic example conf from [jswilder/docker-gen](https://github.com/jwilder/docker-gen)

Also this part

> Picking up changes to letsencrypt_user_data
> 
> The container does not actively watch the /app/letsencrypt_user_data file for changes.
> 
> Changes will either be picked up every hour when the service loop execute again, or by using docker exec your-le-container-name-or-id /app/signal_le_service to manually trigger the service loop execution.

So i guess this is where the problem comes from. What is the "signal_le_service" in my case ?

Thank you !

**Comment by buchdag** [comment]
You don't need to use standalone certificates at all in this case. Just follow [basic usage](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage) and use the `LETSENCRYPT_HOST` environment variable on your wordpress container.

```yaml
version: '3.1'

services:

  site:
    image: wordpress
    environment:
      - VIRTUAL_HOST=yourdomain.tld,www.yourdomain.tld,othersite.tld,www.othersite.tld
      - LETSENCRYPT_HOST=yourdomain.tld,www.yourdomain.tld,othersite.tld,www.othersite.tld

 networks:
  default:
    external:
      name: mynetwork
```

Standalone certificates are only meant to be used when you need to create and renew certificates that are not tied to a container environment variable and/or not used for proxying with nginx-proxy.

If you want to use standalone certificates, the variables go into the file that you mount as `/app/letsencrypt_user_data` inside the container.

Using your example, create a file with this content:

```bash
LETSENCRYPT_STANDALONE_CERTS=('web' 'othersite')
LETSENCRYPT_web_HOST=('yourdomain.tld' 'www.yourdomain.tld')
LETSENCRYPT_othersite_HOST=('othersite.tld' 'www.othersite.tld')
```

And mount it inside the LE container as `/app/letsencrypt_user_data`.

I think I kinda see where the confusion with the docker-gen.cfg file came from, I'll try to clarify the doc.

As for the part about picking up change, it means that if you change your /app/letsencrypt_user_data while the container is running, those change won't be picked up right away and you'll have to use a manual command or wait for the next execution of the cert creation / renewal loop (every hour). `/app/signal_le_service` is the actual name of [the script](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/signal_le_service) that you have to use inside the container to trigger this loop.

Also please keep the discussion about this feature on #368
