### ISSUE TITLE
Problem with cert (Docker-Compose)

### ISSUE THREAD

**Issue by Tockra** [JrCs/docker-letsencrypt-nginx-proxy-companion#446]
Hi guys, 

Hostsystem: debian, 
Docker: 18.06.1-ce, build e68fc7a

here is my setup:
```

    nextcloud:
        build: ./build/web
        restart: always
        volumes:
            - ./data/nextcloud/files/:/var/www/html:ro
        environment:
            VIRTUAL_HOST: nextcloud.oh12.de,homemedia
            LETSENCRYPT_HOST: oh12.de,nextcloud.oh12.de,www.nextcloud.oh12.de
            LETSENCRYPT_EMAIL: myMail
        depends_on:
            - nextcloud-app
        networks:
            - proxy-tier
            - default

 web:
        build: ./build/proxy
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/proxy/certs/:/etc/nginx/certs
            - ./data/proxy/vhost.d/:/etc/nginx/vhost.d
            - ./data/proxy/html/:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - proxy-tier
        depends_on:
            - ssl-certer

 ssl-certer:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - ./data/proxy/certs/:/etc/nginx/certs
            - ./data/proxy/vhost.d/:/etc/nginx/vhost.d
            - ./data/proxy/html/:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
            NGINX_PROXY_CONTAINER: web
        networks:
            - proxy-tier
```

So I start the containers, but the certer seems not to create certificates.
When I restart the certer manualy I get this Error:

```
2018-10-01 09:28:21,343:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-staging.api.letsencrypt.org/acme/authz/ZYPRXlZGRXIKp5H0hX-iMBxkK18jMh7-kR08oQpzzbg, https://acme-staging.api.letsencrypt.org/acme/authz/a8DrtRPZLQ6F1CeOxyWWLLbCcIrLpROxYZtMqBsH-Ks
ssl-certer_1          | Challenge validation has failed, see error log.
```
