### ISSUE TITLE
[Improvement] Skip letsencrypt when host is a subdomain of localhost

### ISSUE THREAD

**Issue by blackandred** [JrCs/docker-letsencrypt-nginx-proxy-companion#449]
Hello,

I have a design pattern where I can append a SUFFIX domain to every service in the network.
This allows me to run all of the services locally very easy by just setting ".localhost" as the domain suffix in the .env file. 

Unfortunately the letsencrypt is trying to generate certificates for such domain as `iwa-ait.org.localhost`. I consider it as an improvement, because when I get a ban for IP for home computer it is not critical for me.

**Comment by buchdag** [comment]
Hi. Could you provide a more detailed example ?

I don't really get what you are doing and if that feature migth benefit others or if it's too specific to you own setup.

**Comment by blackandred** [comment]
Hi.

Sure.
Let's assume we have a docker-compose and .env file.

On dev machine:
DOMAIN_SUFFIX=.localhost

On prod machine:
DOMAIN_SUFFIX=

And that configuration:
```yaml
app_web_mattermost:
        image: mattermost/mattermost-prod-web
        depends_on:
            - app_mattermost
        environment:
            - APP_HOST=app_mattermost
            - APP_PORT=8000

            # gateway configuration
            - VIRTUAL_HOST=mattermost.anarchista.net${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=80
```

On local dev machine I can access it with
https://mattermost.anarchista.net.localhost without any DNS configuration,
tricky - because it's a subdomain of localhost.
On prod machine I can access it by normal host :)

Have a nice day.
