### ISSUE TITLE
Docker-compose Migration & Nginx Configuration

### ISSUE THREAD

**Issue by sako0938** [JrCs/docker-letsencrypt-nginx-proxy-companion#468]
Hello, I am trying to get this project working (again) with docker-compose. I have in the past got it working with docker, but now redoing it with compose I am getting no luck.

Firstly, I am worried that that I in my "application nginx container" (running either reactJS or django) I have changed a setting that is making the letsencrypt challenge fail. In the past I had to do zero configuration of the nginx.conf to make a special route for /.well-known/acme-challenge/X.

1. Do I need something like this in my application container? I thought it was handled by the nginx reverse proxy outer container, but I am not sure: 
```
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /home/mycomp/challenge/.well-known/acme-challenge/;
    }
```

2. Here is my latest docker-compsose.yml, recently have been starting to use the NGINX-PROXY-CONTAINER environment variables, instead of the label, but it still isnt working. 
```
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/mycomp/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /home/mycomp/challenge:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - baby-net
  
  ssl-helper:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-helper
    depends_on:
      - "nginx-proxy"
    volumes:
      - /home/mycomp/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /home/mycomp/challenge:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - baby-net

  mycomp-www:
    depends_on:
      - "ssl-helper"
    build:
      context: ./mycomp-WWW/
    container_name: mycomp-www
    environment:
      - VIRTUAL_HOST=${DOMAIN_WWW}
      - LETSENCRYPT_HOST=${DOMAIN_WWW}
      - LETSENCRYPT_EMAIL=rohit@mycompmicro.com
      # - LETSENCRYPT_TEST=true
    networks:
      - baby-net

networks:
  baby-net:
    driver: bridge
```

Please let me know if you have any ideas. If I get something going, I will try and go back and make a pull request to https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples so get a docker-compose v3 example in there.
