### ISSUE TITLE
Unable to parse template: open /etc/docker-gen/templates/nginx.tmpl: permission denied

### ISSUE THREAD

**Issue by 89ece6d9e021e** [JrCs/docker-letsencrypt-nginx-proxy-companion#470]
Hello Guys,

I know that this error was agitated a few times but I decided to write about it because I couldn't find working solution for me.

###  P R O B L E M
Probably I'm blind or I miss something :/

Kindly I ask you for help to solve that.

```
docker logs dockerGen
2018/11/20 11:04:36 Unable to parse template: open /etc/docker-gen/templates/nginx.tmpl: permission denied
```

```
docker logs nginxLE
Error: can't write to the '/etc/nginx/certs' directory !
Check that '/etc/nginx/certs' directory is export as a writable volume.
```

Below you can find my docker-compose file.
```
version: '2'

services:

  ### N G I N X ###
  nginxServer:
    image: nginx
    container_name: nginxServer
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "/docker/nginx/certs:/etc/nginx/certs" 
      - "/docker/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/docker/nginx/conf.d:/etc/nginx/conf.d"
      - "/docker/nginx/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  ### D O C K E R - G E N ###
  dockerGen:
    image: jwilder/docker-gen
    container_name: dockerGen
    restart: always
    depends_on:
      - nginxServer
    volumes_from:
      - nginxServer
    volumes:
      - "/docker/nginx/templates:/etc/docker-gen/templates"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    command:
      "-notify-sighup nginxServer -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

  ### L E T S - E N C R Y P T ###
  letsEncrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginxLE
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: "nginxServer"
      NGINX_DOCKER_GEN_CONTAINER: "dockerGen"
    depends_on:
      - nginxServer
    volumes_from:
      - nginxServer
    volumes:
      - "/docker/nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

Here you can find output of ls in /docker/nginx dir.
```
myUser@Brix /docker/nginx % l
razem 0
drwxrwxrwx. 5 myUser myUser 44 11-19 19:36 backup
drwxrwxrwx. 2 myUser myUser  6 11-19 19:47 certs
drwxrwxrwx. 2 myUser myUser  6 11-19 19:47 conf.d
drwxrwxrwx. 2 myUser myUser  6 11-19 19:47 html
drwxrwxrwx. 2 myUser myUser 24 11-19 20:52 templates
drwxrwxrwx. 2 myUser myUser  6 11-19 19:47 vhost.d
```
in templates:
```
myUser@Brix /docker/nginx % l templates 
razem 16
-rwxrwxrwx. 1 myUser myUser 16288 11-19 19:37 nginx.tmpl
```
