### ISSUE TITLE
[v1.9.1][python] SystemError on Creating/renawal operation

### ISSUE THREAD

**Issue by BastienM** [JrCs/docker-letsencrypt-nginx-proxy-companion#473]
Hi,

The companion is hitting a wall during the creation/renewal certificate process.
Tried multiple versions (`latest`, `v1.9.1` and `stable`) with the same result.

Also the ACME endpoint is alright: 

```json
$ curl https://acme-v01.api.letsencrypt.org/directory
{
  "4bSMYgEKvm8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
```

Any idea or pointers on what I could have done wrong here ?

#### Logs
```
nginx-proxy-acme_1_152417fdd2a2 | Sleep for 3600s
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:17:59 Generated '/app/letsencrypt_service_data' from 2 containers
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:17:59 Running '/app/update_certs'
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:17:59 Watching docker events
nginx-proxy-acme_1_152417fdd2a2 | Sleep for 3600s
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:17:59 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:17:59 Received event start for container 82ded9061e24
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:18:14 Debounce minTimer fired
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:18:14 Generated '/app/letsencrypt_service_data' from 3 containers
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:18:14 Running '/app/update_certs'
nginx-proxy-acme_1_152417fdd2a2 | /etc/nginx/certs/sub.domain.tld /app
nginx-proxy-acme_1_152417fdd2a2 | Reloading nginx proxy (279a22f36ccd5ea1df2285d94b91c6483f2ab9e6c31d6a45a3f3decea995ec61)...
nginx-proxy-acme_1_152417fdd2a2 | Q2018/11/23 16:18:15 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
nginx-proxy-acme_1_152417fdd2a2 | �2018/11/23 16:18:15 [notice] 40#40: signal process started
nginx-proxy-acme_1_152417fdd2a2 | 2018/11/23 16:18:15 [alert] 40#40: kill(27, 1) failed (1: Operation not permitted)
nginx-proxy-acme_1_152417fdd2a2 | nginx: [alert] kill(27, 1) failed (1: Operation not permitted)
nginx-proxy-acme_1_152417fdd2a2 | Creating/renewal sub.domain.tld certificates... (sub.domain.tld)
nginx-proxy-acme_1_152417fdd2a2 | 2018-11-23 16:18:16,165:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
nginx-proxy-acme_1_152417fdd2a2 | Traceback (most recent call last):
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1558, in main
nginx-proxy-acme_1_152417fdd2a2 |     return main_with_exceptions(cli_args)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1539, in main_with_exceptions
nginx-proxy-acme_1_152417fdd2a2 |     args.tos_sha256 = get_le_tos_hash(LE_PRODUCTION_URI)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 229, in get_le_tos_hash
nginx-proxy-acme_1_152417fdd2a2 |     le_directory = requests.get(le_uri).json()
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
nginx-proxy-acme_1_152417fdd2a2 |     return request('get', url, params=params, **kwargs)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
nginx-proxy-acme_1_152417fdd2a2 |     return session.request(method=method, url=url, **kwargs)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
nginx-proxy-acme_1_152417fdd2a2 |     resp = self.send(prep, **send_kwargs)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
nginx-proxy-acme_1_152417fdd2a2 |     r = adapter.send(request, **kwargs)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
nginx-proxy-acme_1_152417fdd2a2 |     timeout=timeout
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
nginx-proxy-acme_1_152417fdd2a2 |     chunked=chunked)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
nginx-proxy-acme_1_152417fdd2a2 |     self._validate_conn(conn)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
nginx-proxy-acme_1_152417fdd2a2 |     conn.connect()
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 314, in connect
nginx-proxy-acme_1_152417fdd2a2 |     cert_reqs=resolve_cert_reqs(self.cert_reqs),
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 274, in create_urllib3_context
nginx-proxy-acme_1_152417fdd2a2 |     context.verify_mode = cert_reqs
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 400, in verify_mode
nginx-proxy-acme_1_152417fdd2a2 |     _verify_callback
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1061, in set_verify
nginx-proxy-acme_1_152417fdd2a2 |     self._verify_helper = _VerifyHelper(callback)
nginx-proxy-acme_1_152417fdd2a2 |   File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 337, in __init__
nginx-proxy-acme_1_152417fdd2a2 |     "int (*)(int, X509_STORE_CTX *)", wrapper)
nginx-proxy-acme_1_152417fdd2a2 | SystemError: error return without exception set
nginx-proxy-acme_1_152417fdd2a2 |
nginx-proxy-acme_1_152417fdd2a2 | Unhandled error has happened, traceback is above
```

#### docker-compose
```yaml
version: '2'

services:
  some-service:
    image: some-container:latest
    container_name: some-container
    depends_on:
     - nginx-proxy
     - nginx-proxy-acme
    volumes:
     - some-service:/data
    environment:
     VIRTUAL_HOST: sub.domain.tld, www.sub.domain.tld
     VIRTUAL_PORT: 5000
     LETSENCRYPT_HOST: sub.domain.tld
     LETSENCRYPT_EMAIL: mail@awesome.tld
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine # or alpine-0.7.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/syncserver/ssl:/etc/nginx/certs
      - /opt/syncserver/nginx/vhost.d:/etc/nginx/vhost.d
      - /opt/syncserver/nginx/html:/usr/share/nginx/html
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-acme:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
```
