### ISSUE TITLE
CA marked some of the authorizations as invalid?

### ISSUE THREAD

**Issue by brandex007** [JrCs/docker-letsencrypt-nginx-proxy-companion#501]
For some reason I keep getting "CA marked some of the authorizations as invalid" error. Any ideas why? I was able to get Letsencrypt working on the host (migrating to docker) so I know the problem is here. 

My docker-compose file:
```
version: '2'
services:
  ghost:
    image: ghost:latest
    volumes:
      - ./ghost-db/:/var/lib/ghost/content/
    expose:
      - "2368"
    environment:
      url: https://bakeitcookbook.com
      VIRTUAL_HOST: bakeitcookbook.com,www.bakeitcookbook.com
      LETSENCRYPT_HOST: bakeitcookbook.com,www.bakeitcookbook.com
      LETSENCRYPT_EMAIL: bkalashian@gmail.com
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    links:
      - ghost
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy                                                                                                                                                      
```
