### ISSUE TITLE
Problem with sub domain

### ISSUE THREAD

**Issue by 89ece6d9e021e** [JrCs/docker-letsencrypt-nginx-proxy-companion#508]
Hello Guys,

I have problem with configuration for sub-domain.

Below you can find my configurations:

```
For domain:

  my-domain:
    image: nginx
    container_name: my-domain.com
    depends_on:
      - nginxServer
      - dockerGen
      - letsEncrypt
    volumes:
      - "/docker/www/my-domain.com:/usr/share/nginx/html"
    environment:
      - VIRTUAL_HOST=my-domain.com
      - LETSENCRYPT_HOST=my-domain.com
      - LETSENCRYPT_EMAIL=office@my-domain.com
```
and
```
For sub-domain:

test.my-domain.com:
    image: wordpress
    container_name: test.my-domain.com
    depends_on:
      - nginxServer
      - dockerGen
      - letsEncrypt
      - db
    environment:
      - VIRTUAL_HOST=test.my-domain.com
      - LETSENCRYPT_HOST=test.my-domain.com
      - LETSENCRYPT_EMAIL=office@my-domain.com
```

Domain is working ok but when I'm trying to get sub-domain I get message from browser that is wrong certificate configuration. Could you show me what I'm doing wrong?
