### ISSUE TITLE
Help: http working, but 500 https 

### ISSUE THREAD

**Issue by eduzen** [JrCs/docker-letsencrypt-nginx-proxy-companion#509]
Hi, I'm working on dockerize a project with jwilder/nginx-proxy and docker-letsencrypt-nginx-proxy-companion.  I have a lot of webapp, but Im trying to figure it out just with one working.

Everything is working with http, but when Im trying to access through https, I see the insecure certificate and after I accepted I see 500 Internal Server Error - nginx/1.14.1.

Logs of nginx-proxy show me ` "GET / HTTP/2.0" 500 595 "-" "Mozilla/5.0 ....`
Letsencrypt doesn't show me bad things.
www doesn't log anything.

What im doing wrong?

Thanks!

```yaml
version: '3.2'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx:1.14.2-alpine
    restart: always
    expose:
      - 80
    volumes:
      - ./config/nginx/conf.d/hive.conf:/etc/nginx/conf.d/default.conf:ro
      - backend:/opt/path/backend:ro
      - static:/opt/path/static:ro
      - media:/opt/path/media
      - frontend:/opt/path/frontend:ro
    environment:
      - VIRTUAL_HOST=foo.bar
      - LETSENCRYPT_HOST=foo.bar
      - LETSENCRYPT_EMAIL=foo.bar@foo.bar
    networks:
      - nginx_network

  php:
    image: php...
    expose:
      - 9000
    environment:
      - VIRTUAL_PORT=9000
    volumes:
      - backend:/opt/path/backend
    depends_on:
      - "mysql"
    networks:
      - database_network
      - nginx_network

  hive-api:
    image: django...
    command: ["sh", "/code/scripts/gunicorn_start.sh"]
    expose:
      - 8001
    volumes:
      - static:/code/static
      - media:/code/media
      - logs:/code/logs
    environment:
      - SECRET_KEY=changemeinprod
      - DB_USER=foo
      - DB_NAME=bar
      - DB_PASS=foo
      - DB_SERVICE=mysql
      - DEBUG=False
    depends_on:
      - mysql
    networks:
      - database_network
      - nginx_network

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  certs:
  html:
  vhostd:
  static:
  media:
  backend:
  frontend:
  dbdata:
  logs:
networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge
```

I have a basic config for www container but is only a http config.
