### ISSUE TITLE
Does not restore original vhosts configuration

### ISSUE THREAD

**Issue by Redsandro** [JrCs/docker-letsencrypt-nginx-proxy-companion#521]
When using [Per-VIRTUAL_HOST configuration](https://github.com/jwilder/nginx-proxy#per-virtual_host), for example to set rewrite or redirect rules, the `docker-letsencrypt-nginx-proxy-companion` prepends some custom code, and doesn't clean up nor restore the original file afterwards.

The files are left in `/etc/nginx/vhost.d` with the temporary code prepended, and the entire nginx server won't work.

For example, `/etc/nginx/vhost.d/windowsremix.com` before starting this companion:
```
return 301 https://www.windowsremix.com$request_uri;
```

`/etc/nginx/vhost.d/windowsremix.com` after this companion:
```
## Start of configuration add by letsencrypt container
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
return 301 https://www.windowsremix.com$request_uri;
```

Removing all custom vhost configuration and restarting the stack brings up the server again. Although of course without custom rewrite or redirect rules.

**Comment by buchdag** [comment]
Hi. I'll try to take a look at this soon.

**Comment by Faerbit** [comment]
I had the same problem and fiddled a bit with it.
My setup is something like this
```yml
# docker-compose.yml
volumes:
    vhostd:
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes:
            - vhostd:/etc/nginx/vhost.d
            - /path/to/config/nginx.conf:/etc/nginx/example.com
    letsencrypt:
        image: JrCs/docker-letsencrypt-nginx-proxy-companion
        volumes:
            - vhostd:/etc/nginx/vhost.d
```
(Shortended to the relevant bits)
I modified /app/functions.sh a bit to be able to look at the original `nginx.conf` mounted as `example.com`, before it is modified by the `letsencrypt_service` (via `functions.sh:add_location_configuration`) script.
In this configuration the file `example.com` exists but is empty, which leads to the behaviour described in the OP.
I am not sure if this intendended behaviour or a bug, and if the bug is within docker or docker-compose, so I am unsure how one would proceed with this problem. 
Simply moving the volume declaration like this:
```yml
# docker-compose.yml
volumes:
    vhostd:
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes:
            - vhostd:/etc/nginx/vhost.d

    letsencrypt:
        image: JrCs/docker-letsencrypt-nginx-proxy-companion
        volumes:
            - vhostd:/etc/nginx/vhost.d
            - /path/to/config/nginx.conf:/etc/nginx/example.com
```
Produces `/etc/nginx/example.com.new` which looks like it should, but the `mv`, which copies the `example.com.new` to `example.com` fails.
For the moment I settled to a manually created file which contains my configuration directive and the ones from this container, and mounted this file to both containers.

**Comment by Redsandro** [comment]
Thank you @Faerbit for your insights!

For the time being as long as I can get away with it, I'm using https://hub.docker.com/r/morbz/docker-web-redirect/ to redirect things. This is only a workaround for a specific use case. I think something needs to be rewritten (or documented), but I'm not sure where. I'm hoping someone more knowledgeable than me will remedy this before it's time for me to require more complex configurations.

**Comment by Redsandro** [comment]
[Reverting accidental close]

**Comment by buchdag** [comment]
@Faerbit when using Docker bind mount (ie mounting a single file or directory inside a container), you have to configure the bind mount on **every container** that will need access to this file, either by using the `volumes-from` option or by mounting it explicitly inside each container. 

So the correct configuration snippets would either be :

```yaml
# docker-compose.yml
volumes:
    vhostd:
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        volumes:
            - vhostd:/etc/nginx/vhost.d
            - /path/to/config/nginx.conf:/etc/nginx/example.com
    
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes_from:
            - nginx-proxy
```

or :

```yaml
# docker-compose.yml
volumes:
    vhostd:
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes:
            - vhostd:/etc/nginx/vhost.d
            - /path/to/config/nginx.conf:/etc/nginx/example.com
    
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
         volumes:
            - vhostd:/etc/nginx/vhost.d
            - /path/to/config/nginx.conf:/etc/nginx/example.com
```

note that `volumes_from` is only available in compose file version 2.
