### ISSUE TITLE
HELP: Error: can't get nginx-proxy container id !

### ISSUE THREAD

**Issue by cmivxx** [JrCs/docker-letsencrypt-nginx-proxy-companion#534]
Not sure if this is the right place to put this, but I've got an error that I have double and triple checked and it's just not cooperating.  Here's the error:

```
Error: can't get nginx-proxy container id !
Check that you use the --volumes-from option to mount volumes from the nginx-proxy or label the nginx proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'.
```

And here is my `docker-compose.yml` file (addresses and pw's changed)

```
version: "3"
services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: nginx-proxy
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
       - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
       - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
       - /apps/docker-articles/nginx/html:/usr/share/nginx/html
     labels:
       - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

   letsencrypt:
     image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
     container_name: nginx-certs
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
       - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
       - /apps/docker-articles/nginx/html:/usr/share/nginx/html

   wordpress_a:
     image: wordpress:latest
     container_name: wpa
     restart: always
     environment:
       VIRTUAL_HOST: core-a.mydomain.com
       VIRTUAL_PORT: 8001
       LETSENCRYPT_HOST: core-a.mydomain.com
       LETSENCRYPT_EMAIL: email@mydomain.com
       WORDPRESS_DB_HOST: db01.myotherdomain.com:3306
       WORDPRESS_DB_USER: coretestwp
       WORDPRESS_DB_PASSWORD: testpassworda
       WORDPRESS_DB_NAME: test_wpa

   wordpress_b:
     image: wordpress:latest
     container_name: wpb
     restart: always
     environment:
       VIRTUAL_HOST: core-b.mydomain.com
       VIRTUAL_PORT: 8002
       LETSENCRYPT_HOST: core-b.mydomain.com
       LETSENCRYPT_EMAIL: cm@mydomain.com
       WORDPRESS_DB_HOST: db01.myotherdomain.com:3306
       WORDPRESS_DB_USER: coretestwp
       WORDPRESS_DB_PASSWORD: testpasswordb
       WORDPRESS_DB_NAME: test_wpb

networks:
  default:
    external:
      name: web
```

Server is a CoreOS box on DO.

The server is responding just fine on Port 80, but the SSL portion doesn't function at all, not even a certificate error.  So I am super confused as to how I can try to fix this to make it run properly.  I'm about to abandon this and go for Traefik or HAProxy if I can't get it running.

Any help would be greatly appreciated.
