### ISSUE TITLE
LetsEncrypt challenge fails with nginx-proxy:latest

### ISSUE THREAD

**Issue by elifiner** [JrCs/docker-letsencrypt-nginx-proxy-companion#544]
I'm using the following `docker-compose.yml` with `nginx-proxy:latest` and getting an error (see below). Using `nginx-proxy:alpine` in this setup works fine.

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.mp0.rbgapp.com
      - LETSENCRYPT_HOST=whoami.mp0.rbgapp.com
```

And getting the following error:

```
nginx-proxy-letsencrypt_1  | 2019-05-19 03:00:11,836:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/_o4LwxfsGhU_5nmrqrX94whYgjf4RUlsM1U9RjkJ-I0
```

Looking at https://acme-v01.api.letsencrypt.org/acme/authz/_o4LwxfsGhU_5nmrqrX94whYgjf4RUlsM1U9RjkJ-I0 it seems `nginx-proxy` just called the `whoami` container and didn't respond with the LE challenge.

Might be enough to just mention in the README that this only supports the (newer?) alpine image.
