### ISSUE TITLE
Configuring certificates for docker-mailserver

### ISSUE THREAD

**Issue by rhyst** [JrCs/docker-letsencrypt-nginx-proxy-companion#572]
Hey,

I'm trying to get certificates generated for a docker-mail-server container to use. I have the mail server container starting with the following config:

```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.tld
    ports:
    - "25:25"
    - "587:587"
    - "993:993"
    - "995:995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/certs/mail.domain.tld:/etc/letsencrypt/live/mail.domain.tld
    depends_on:
     - NGINX_PROXY
     - NGINX_PROXY_LETSENCRYPT
    networks:
     - NGINX_PROXY_NETWORK
    environment:
    - VIRTUAL_HOST=mail.domain.tld
    - LETSENCRYPT_HOST=mail.domain.tld
    - LETSENCRYPT_EMAIL=email@gmail.com

... (lots of mail-server env vars)

```

The mail server uses the certificates correctly if they are present, but letsencrypt companion fails to renew the certificates.

```
CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain 
```

I'm not quite sure how the challenge works so I'm not sure if the mail server container needs to be able to host the well-known auth. I have other containers that work perfectly with letsencrypt companion and they do not seem to need to know anything about the challenge.

Any help is appreciated. Thanks.
