### ISSUE TITLE
Problem Validation Certs

### ISSUE THREAD

**Issue by Todosio** [JrCs/docker-letsencrypt-nginx-proxy-companion#579]
See, you can help me with this, please, 

I'm trying to install a docker-letsencrypt-nginx-proxy-companion certificate on my domain tool.eraenti.info and I'm encountering this problem when it tries to generate the domain and I can't move forward.

2019-09-20 16:10:29,298:INFO:simp_le:1479: Generating new certificate private key
2019-09-20 16:10:29,910:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz-v3/428025727
Challenge validation has failed, see error log.

on my other server works well the same, but the AWS does not work

**Comment by huuchi207** [comment]
I have same issue. Waiting for solution.

**Comment by buchdag** [comment]
Hi. Have you followed the troubleshooting hints at https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md ?

**Comment by huuchi207** [comment]
I get rid of problem by correct the path of nginx.tmpl file.

**Comment by CarolusMagnus** [comment]
Same problem here with standalone certificates, after updating to newest dev version.

**Comment by kelsotodd** [comment]
Hi there. I'm having issues with renewing a cert. Solution worked for three months but renewal has failed since then.

I've followed the invalid authorizations steps and they all seem to check out.

I get the following failures:

"status": "invalid",
nextcloud-letsencrypt |   "expires": "2019-11-21T19:13:13Z",
nextcloud-letsencrypt |   "challenges": [
nextcloud-letsencrypt |     {
nextcloud-letsencrypt |       "type": "http-01",
nextcloud-letsencrypt |       "status": "invalid",
nextcloud-letsencrypt |       "error": {
nextcloud-letsencrypt |         "type": "urn:ietf:params:acme:error:connection",
nextcloud-letsencrypt |         **"detail": "Fetching http://[redacted]/.well-known/acme-challenge/mWvjEWpojMYwqGASVg9QqKSC70KDm3YXq5sMS1AgNJY: Connection refused",**
nextcloud-letsencrypt |         "status": 400
nextcloud-letsencrypt |       },
nextcloud-letsencrypt |       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/1239035323/JY-1Ug",
nextcloud-letsencrypt |       "token": "mWvjEWpojMYwqGASVg9QqKSC70KDm3YXq5sMS1AgNJY",
nextcloud-letsencrypt |       "validationRecord": [
nextcloud-letsencrypt |         {
nextcloud-letsencrypt |           "url": "http://[redacted]/.well-known/acme-challenge/mWvjEWpojMYwqGASVg9QqKSC70KDm3YXq5sMS1AgNJY",
nextcloud-letsencrypt |           "hostname": "[redacted]",
nextcloud-letsencrypt |           "port": "80",
nextcloud-letsencrypt |           "addressesResolved": [
nextcloud-letsencrypt |             "157.245.5.138"
nextcloud-letsencrypt |           ],
nextcloud-letsencrypt |           "addressUsed": "157.245.5.138"
nextcloud-letsencrypt |         }
nextcloud-letsencrypt |       ]
nextcloud-letsencrypt |     },
nextcloud-letsencrypt |     {
nextcloud-letsencrypt |       "type": "dns-01",
nextcloud-letsencrypt |       "status": "invalid",
nextcloud-letsencrypt |       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/1239035323/1Msr8w",
nextcloud-letsencrypt |       "token": "mWvjEWpojMYwqGASVg9QqKSC70KDm3YXq5sMS1AgNJY"
nextcloud-letsencrypt |     },
nextcloud-letsencrypt |     {
nextcloud-letsencrypt |       "type": "tls-alpn-01",
nextcloud-letsencrypt |       "status": "invalid",
nextcloud-letsencrypt |       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/1239035323/Wl3HqQ",
nextcloud-letsencrypt |       "token": "mWvjEWpojMYwqGASVg9QqKSC70KDm3YXq5sMS1AgNJY"
nextcloud-letsencrypt |     }
nextcloud-letsencrypt |   ]

The bolded statement seems to be the culprit, but I cannot fathom how to resolve it as the base containers did not change. I've even pulled the updates to all containers without success. I'd appreciate any pointers. Thanks!

**Comment by binarious** [comment]
Having the same problem. Error details from Let's Encrypt:
```
"challenges": [
  {
    "type": "http-01",
    "status": "invalid",
    "error": {
      "type": "urn:ietf:params:acme:error:connection",
      "detail": "Fetching https://REMOVED/.well-known/acme-challenge/7MTvqndpaS7l6xDHXPIqLYLdtesp3Gy-heC3omgkRuQ: Error getting validation data",
      "status": 400
    }
    // ...
  }
]
```
<details><summary>My docker-compose.yml</summary>
```
version: '3'

services:
  db:
    image: mariadb:10.4
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REMOVED
    env_file:
      - db.env

  redis:
    image: redis:5.0-alpine
    restart: always

  app:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=REMOVED
      - LETSENCRYPT_HOST=REMOVED
      - LETSENCRYPT_EMAIL=REMOVED
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/nextcloud"
  db:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
</details>

**Comment by binarious** [comment]
Found my problem. `nginx-proxy` has HSTS activated which rejects the acme-challenge on an expired certificate. Had to add `HTTPS_METHOD=noredirect` to the proxy temporarily, restart the containers and the certs have been renewed.

**Comment by kelsotodd** [comment]
Hi @binarious thanks for the pointer!

Can you please share your config that you used to fix the issue?

I've tried an environmental variable on the proxy but it doesn't solve the issue:

```
environment:
    - HTTPS_METHOD=noredirect
```

Thanks!

**Comment by binarious** [comment]
@kelsotodd I have added it to 'web'. Sorry, it wasn't the `nginx-proxy`, but the normal `nginx`:

<details><summary>My docker-compose.yml</summary>

```
version: '3'

services:
  db:
    image: mariadb:10.4
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REMOVED
    env_file:
      - db.env

  redis:
    image: redis:5.0-alpine
    restart: always

  app:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=REMOVED
      - LETSENCRYPT_HOST=REMOVED
      - LETSENCRYPT_EMAIL=REMOVED
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/nextcloud"
  db:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
</details>

1. Change the file 
1. `docker-compose up -d`
1. The cert should now be renewed
1. Revert the file and restart the services again

Hope that works for you aswell.
