### ISSUE TITLE
LETSENCRYPT not creating certs for multiple domains in single container sharing port 80.

### ISSUE THREAD

**Issue by laurencefass** [JrCs/docker-letsencrypt-nginx-proxy-companion#585]
I have a single nginx proxying multiple domains defined in a docker-compose.yml file. Only port 80 is exposed on the container. LetsEcnrypt container is not creating cert files on docker-compose up.

Though none of the proxy settings have https enabled or certs of their own when I try to access any of the domains listed the browser returns with a NET::ERR_CERT_COMMON_NAME_INVALID.

Inspecting the LE container's /etc/nginx/certs folder there are no symlinks for chain, crt, dhparam.pem and key files for any of the domains listed in the docker-compose file. only a folder for the first domain listed.

```
bash-4.4# pwd
/etc/nginx/certs

bash-4.4# ls -la apps.syntapse.co.uk
total 12
drwxr-xr-x  2 root root 4096 Oct  9 13:00 .
drwxr-xr-x 18 root root 4096 Oct  9 12:13 ..
lrwxrwxrwx  1 root root   63 Oct  9 13:00 account_key.json -> ../accounts/acme-v01.api.letsencrypt.org/directory/default.json
```

docker-compose file looks like this:

```
services:
  # apps = pm2 node.js server and combined nginx proxy for url=>port routing
  apps:
    container_name: apps
    image: lfass/nodejsbase
    hostname: apps.syntapse.co.uk
    expose:
    - "80"
    environment:
    - VIRTUAL_HOST=apps.syntapse.co.uk, contenta.syntapse.co.uk, next.syntapse.co.uk, nuxt.syntapse.co.uk,gatsby.syntapse.co.uk, angular.syntapse.co.uk, react.syntapse.co.uk, vue.syntapse.co.uk
    - LETSENCRYPT_HOST=apps.syntapse.co.uk, contenta.syntapse.co.uk, next.syntapse.co.uk, nuxt.syntapse.co.uk,gatsby.syntapse.co.uk, angular.syntapse.co.uk, react.syntapse.co.uk, vue.syntapse.co.uk
    - LETSENCRYPT_EMAIL=xxxx.xxx
    volumes:
    - etc:/etc
    networks:
       wilderproxynet:

....
# using the same network as jwilder docker proxy and companion
networks:
  wilderproxynet:
    external:
      name: wilderproxynet
```

I am happy to provide logs or further information to help understand why no certs are created only a single folder...
