### ISSUE TITLE
Unreadable volumes when running from docker compose with nginx-proxy

### ISSUE THREAD

**Issue by sifotes** [JrCs/docker-letsencrypt-nginx-proxy-companion#597]
Logs on startup:
```
Creating network "docker-le-proxy_default" with the default driver
Creating nginx-proxy       ... done
Creating proxy-letsencrypt ... done
Attaching to proxy-letsencrypt, nginx-proxy
nginx-proxy                | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy                | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy                | dhparam: Can't parse "false" as a number
nginx-proxy                | forego     | starting dockergen.1 on port 5000
nginx-proxy                | forego     | starting nginx.1 on port 5100
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:07 Generated '/etc/nginx/conf.d/default.conf' from 7 containers
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:07 Running 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:07 Watching docker events
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:07 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:07 Received event die for container 1cea947e704a
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:08 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:08 Received event start for container 1cea947e704a
proxy-letsencrypt          | Error: can't access to '/etc/nginx/certs' directory !
proxy-letsencrypt          | Check that '/etc/nginx/certs' directory is declared as a writable volume.
proxy-letsencrypt          | Warning: '/etc/nginx/certs' does not appear to be a mounted volume.
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:08 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2019/11/05 06:02:08 Received event die for container 1cea947e704a
proxy-letsencrypt          | Warning: '/etc/nginx/certs' does not appear to be a mounted volume.
proxy-letsencrypt          | Error: can't access to '/etc/nginx/certs' directory !
proxy-letsencrypt          | Check that '/etc/nginx/certs' directory is declared as a writable volume.
```
proxy-letsencrypt being this project. 
The local folders being mounted are created on start up, I haven't set the permissions or restricted the read access in an way. 
My compose file:

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DHPARAM_GENERATION=false
    volumes:
      - ./nginx-certs:/etc/ngnix/certs
      - ./nginx-vhosts:/etc.ngninx-vhosts.d/
      - ./nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-letsencrypt
    environment:
      - DEFAULT_EMAIL=[EMAIL]
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginx-certs:/etc/ngnix/certs
      - ./nginx-vhosts:/etc.ngninx-vhosts.d
      - ./nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

```
