### ISSUE TITLE
Simply Doesnt Work

### ISSUE THREAD

**Issue by patsadow2** [JrCs/docker-letsencrypt-nginx-proxy-companion#604]
![image](https://user-images.githubusercontent.com/19226186/70847279-1a4beb00-1e63-11ea-9ac8-bc16b416ffa0.png)

docker kill $(docker ps -q)
docker rm $(docker ps -a -q)

docker run --detach --name nginx-proxy --publish 80:80 --publish 443:443 --volume /etc/nginx/certs --volume /etc/nginx/vhost.d --volume /usr/share/nginx/html --volume /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

docker run --detach --name nginx-proxy-letsencrypt --volumes-from nginx-proxy --volume /var/run/docker.sock:/var/run/docker.sock:ro --env "DEFAULT_EMAIL=pat323@gmail.com" jrcs/letsencrypt-nginx-proxy-companion

```
version: '3.6'

services:
  ihoste:
    image: xxxd
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=api.test01.xxxd.com
      - LETSENCRYPT_HOST==api.test01.xxxd.com
    ports:
      - "6100:80"
      - "6150:443"

networks:
  default:
    external:
      name: webproxy
```

No HTTPS only 502 :<
