### ISSUE TITLE
does not work with sharelatex

### ISSUE THREAD

**Issue by guitar9** [JrCs/docker-letsencrypt-nginx-proxy-companion#608]
I tested it with grafana and everything works fine.
Now i want to use sharelatex (overleaf)
All I get is 502 Bad Gateway when I call latex.kwant.de

When I call it with
http://tkwant.de:8080

everything works fine. 

This my docker compose

```
version: '3'

services:
  sharelatex:
    restart: always
    # Server Pro users:
    # image: quay.io/sharelatex/sharelatex-pro
    image: sharelatex/sharelatex
    container_name: sharelatex
    privileged: true
    ports:
        - 8080:80
    depends_on:
        - mongo
        - redis
    links:
        - mongo
        - redis
    volumes:
        - ./docker_data/sharelatex_data:/var/lib/sharelatex
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        VIRTUAL_HOST: latex.tkwant.de
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: latex.tkwant.de
        LETSENCRYPT_EMAIL: t.kwant1@gmail.com
        SHARELATEX_APP_NAME: Overleaf Community Edition
        SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
        # Same property, unfortunately with different names in
        # different locations
        SHARELATEX_REDIS_HOST: redis
        REDIS_HOST: redis
        ENABLED_LINKED_FILE_TYPES: 'url,project_file'
        # Enables Thumbnail generation using ImageMagick
        ENABLE_CONVERSIONS: 'true'
        ## Set for SSL via nginx-proxy
        #VIRTUAL_HOST: 103.112.212.22
        # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
        # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
        # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
        # SHARELATEX_ADMIN_EMAIL: support@it.com
        # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
        # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'
        # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"
        # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
        # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:
        # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
        # SHARELATEX_EMAIL_SMTP_PORT: 587
        # SHARELATEX_EMAIL_SMTP_SECURE: false
        # SHARELATEX_EMAIL_SMTP_USER:
        # SHARELATEX_EMAIL_SMTP_PASS:
        # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
        # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
        # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"
        ################
        ## Server Pro ##
        ################
        # SANDBOXED_COMPILES: 'true'
        # SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
        # SANDBOXED_COMPILES_HOST_DIR: '/var/sharelatex_data/data/compiles'
        # SYNCTEX_BIN_HOST_PATH: '/var/sharelatex_data/synctex'
        # DOCKER_RUNNER: 'false'
        ## Works with test LDAP server shown at bottom of docker compose
        # SHARELATEX_LDAP_URL: 'ldap://ldap:389'
        # SHARELATEX_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
        # SHARELATEX_LDAP_SEARCH_FILTER: '(uid={{username}})'
        # SHARELATEX_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
        # SHARELATEX_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
        # SHARELATEX_LDAP_EMAIL_ATT: 'mail'
        # SHARELATEX_LDAP_NAME_ATT: 'cn'
        # SHARELATEX_LDAP_LAST_NAME_ATT: 'sn'
        # SHARELATEX_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'
        # SHARELATEX_TEMPLATES_USER_ID: "578773160210479700917ee5"
        # SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'
        # SHARELATEX_PROXY_LEARN: "true"
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "127.0.0.1:27017:27017"
  redis:
      restart: always
      image: redis
      container_name: redis
      expose:
          - 6379
      volumes:
          - ./docker_data/redis_data:/dat
```
