### ISSUE TITLE
Django Gunicorn Deploy

### ISSUE THREAD

**Issue by basitiyidir** [JrCs/docker-letsencrypt-nginx-proxy-companion#609]
I'm using Django and Gunicorn.

I publish multiple sites and I can use the 8000 port once.

Is it true?  like I'm making a mistake somewhere

I'm using advanced use to deploy with Docker.  
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Advanced-usage

Thank for help

**Site 1**
```
version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn bahar.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000

    nginx:
        build: ./nginx
        depends_on:
            - web
        expose:
            - "80"
        environment:
           - VIRTUAL_HOST=domain1.domain.com
           - VIRTUAL_NETWORK=nginx-proxy
           - VIRTUAL_PORT=80
           - LETSENCRYPT_HOST=domain1.domain.com
           - LETSENCRYPT_EMAIL=domain@domain.com

networks:
    default:
        external:
            name: nginx-proxy

```

**Site 2**
```
version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn bahar.wsgi:application --bind 0.0.0.0:8001
        expose:
            - 8001

    nginx:
        build: ./nginx
        depends_on:
            - web
        expose:
            - "80"
        environment:
           - VIRTUAL_HOST=domain2.domain.com
           - VIRTUAL_NETWORK=nginx-proxy
           - VIRTUAL_PORT=80
           - LETSENCRYPT_HOST=domain2.domain.com
           - LETSENCRYPT_EMAIL=domain@domain.com

networks:
    default:
        external:
            name: nginx-proxy

```
**nginx.conf site 1**
```
upstream docker_test_site_1 {
    server web:8000;
}

server {

    server_name domain1.domain.com;

    location / {
        proxy_pass http://docker_test_site_1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

}
```
**nginx.conf site 2**
```
upstream docker_test_site_2 {
    server web:8001;
}

server {

    server_name domain2.domain.com;

    location / {
        proxy_pass http://docker_test_site_2;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

}
```
