### ISSUE TITLE
Port 80 already in use

### ISSUE THREAD

**Issue by manish-fn** [JrCs/docker-letsencrypt-nginx-proxy-companion#619]
I have installed this docker app.
https://docs.filerun.com/docker
It is listening on port 80

```yaml
version: ‘2’

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
    volumes:
      - /filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - “80:80”
    volumes:
      - /filerun/html:/var/www/html
      - /filerun/user-files:/user-files
```

How can i also install a certbot letsencrypt in the same container?
