### ISSUE TITLE
Error: could not get a nginx-proxy container ID

### ISSUE THREAD

**Issue by mindrunner** [JrCs/docker-letsencrypt-nginx-proxy-companion#623]
Constantly getting this at one of my customer's servers resulting in an exired certificate.

Restarting companion will bring everything to a working state again and renewing the cert.

What is wrong with my configuration?

```
nginx-proxy-letsencrypt | 2020/02/21 05:51:01 Generated '/app/letsencrypt_service_data' from 5 containers
nginx-proxy-letsencrypt | 2020/02/21 05:51:01 Running '/app/signal_le_service'
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 05:51:01 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 06:51:01 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 07:51:01 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 08:51:01 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 09:51:02 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 10:51:02 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
nginx-proxy-letsencrypt | 2020/02/21 11:38:35 Received event start for container 5763b410174d
nginx-proxy-letsencrypt | 2020/02/21 11:38:42 Received event die for container f1d0ddb40917
nginx-proxy-letsencrypt | 2020/02/21 11:38:44 Received event stop for container f1d0ddb40917
nginx-proxy-letsencrypt | 2020/02/21 11:38:48 Received event start for container 455b1b67a1ea
nginx-proxy-letsencrypt | 2020/02/21 11:39:03 Debounce minTimer fired
nginx-proxy-letsencrypt | 2020/02/21 11:39:03 Generated '/app/letsencrypt_service_data' from 6 containers
nginx-proxy-letsencrypt | 2020/02/21 11:39:03 Running '/app/signal_le_service'
nginx-proxy-letsencrypt | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt | 2020/02/21 11:39:03 Error: could not get a nginx-proxy container ID.
nginx-proxy-letsencrypt | Sleep for 3600s
```

```
version: "2"

services:
  nginx-proxy: 
    image: nginx
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier
    restart: always

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx-proxy
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
