### ISSUE TITLE
Does this only work for subdomains?

### ISSUE THREAD

**Issue by JMDevelopers** [JrCs/docker-letsencrypt-nginx-proxy-companion#625]
environment:
          VIRTUAL_HOST: mywebsite.io
          VIRTUAL_PORT: 80
          LETSENCRYPT_HOST: mywebsite.io
          LETSENCRYPT_EMAIL: josh@mymail.com

So this is what my environment is set up as, if i try to use a domain like this it doesnt seem to work, but as soon as i use a subdomain it does? So my question is does this only work for subdomains and not top level domains ?

**Comment by buchdag** [comment]
Nope, this project woks for top level domains as well as subdomains.

If the authorizations for your top level domain are failing, I suggest reading https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md first.

**Comment by whackur** [comment]
Same issue.

My docker-compose file's bellow
```
  main:
    image: my_image:latest
    container_name: main
    environment:
      - VIRTUAL_HOST=my_image.net
      - LETSENCRYPT_HOST=my_image.net
      - LETSENCRYPT_EMAIL=qwerty@gmail.com
    network_mode: "webproxy"
    restart: always

  shop:
    image: my_shop:latest
    container_name: test-my_image
    environment:
      - VIRTUAL_HOST=shop.my_image.net
      - LETSENCRYPT_HOST=shop.my_image.net
      - LETSENCRYPT_EMAIL=qwerty@gmail.com
    network_mode: "webproxy"
    restart: always
```

But only sub-domain sites working.

This image is latest and I checked port status.




And I tested this code in 'readme.md'

```
docker run -d -e VIRTUAL_HOST=your.domain.com \
              -e LETSENCRYPT_HOST=your.domain.com \
              -e LETSENCRYPT_EMAIL=your.email@your.domain.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine
```

It worked. but my image doesn't work.
