### ISSUE TITLE
simp_le: error: argument -d/--vhost: expected one argument

### ISSUE THREAD

**Issue by jedwards1211** [JrCs/docker-letsencrypt-nginx-proxy-companion#86]
If I put multiple hostnames in `LETSENCRYPT_HOST`, I get the following error:

```
letsencrypt-nginx-proxy-companion    | simp_le: error: argument -d/--vhost: expected one argument
letsencrypt-nginx-proxy-companion    | /app/letsencrypt_service: line 18: 1: missing base_domain argument
```

It already seems to work if I omit the base domain from `LETSENCRYPT_HOST` and just use the subdomain, as shown below.  Is the documentation correct?

```yml
  owncloud:
    container_name: owncloud
    image: owncloud
    volumes:
      - "./private/owncloud/data:/var/www/html"
    ports:
      - 80
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=owncloud.$HOSTNAME
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=owncloud.$HOSTNAME
      - LETSENCRYPT_EMAIL=jedwards@fastmail.com
    networks:
      - proxy-tier
```
