### ISSUE TITLE
Howto specify commandline options for docker-gen in docker-compose.yml

### ISSUE THREAD

**Issue by marcofranssen** [JrCs/docker-letsencrypt-nginx-proxy-companion#96]
Would be cool if there can be added a docker-compose.yml example in the readme.

That will allow people to very quickly get the solution running.

Below is how far I got, however I'm not sure how to provide those commandline options needed for running docker-gen.

```
version: '2'
services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /etc/nginx/conf.d
      - /usr/share/nginx/html

  nginx-gen:
    image: jwilder/docker-gen
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - proxy
    volumes:
      - ~/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen

  web:
    build: ./web
    environment:
      VIRTUAL_HOST: web.domain.tld
      LETSENCRYPT_HOST: web.domain.tld
      LETSENCRYPT_EMAIL: letsencrypt@domain.tld

  api:
    build: ./api
    environment:
      VIRTUAL_HOST: api.domain.tld
      LETSENCRYPT_HOST: api.domain.tld
      LETSENCRYPT_EMAIL: letsencrypt@domain.tld
```
